#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 64
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 37
#define ALIAS_COUNT 0
#define TOKEN_COUNT 17
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 13
#define MAX_ALIAS_SEQUENCE_LENGTH 6
#define PRODUCTION_ID_COUNT 12

enum ts_symbol_identifiers {
  anon_sym_LPAREN = 1,
  anon_sym_RPAREN = 2,
  anon_sym_DOT = 3,
  sym_NAME = 4,
  aux_sym_float_token1 = 5,
  sym__DIGITS = 6,
  sym__SIGN = 7,
  anon_sym_STAR = 8,
  anon_sym_SLASH = 9,
  anon_sym_STAR_STAR = 10,
  aux_sym_unit_token1 = 11,
  anon_sym_u00b0 = 12,
  anon_sym_PERCENT = 13,
  anon_sym_COMMA = 14,
  anon_sym_PLUS = 15,
  anon_sym_DASH = 16,
  sym_expression = 17,
  sym__sub_expression = 18,
  sym_parenthesized_expression = 19,
  sym_variable = 20,
  sym__DOT = 21,
  sym__scalar = 22,
  sym__number = 23,
  sym_integer = 24,
  sym_float = 25,
  sym_quantity = 26,
  sym_units = 27,
  aux_sym__units_mult_part = 28,
  aux_sym__units_div_part = 29,
  sym_unit_term = 30,
  sym_unit = 31,
  sym_call = 32,
  sym_args = 33,
  sym_binary_operator = 34,
  aux_sym_variable_repeat1 = 35,
  aux_sym_args_repeat1 = 36,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_DOT] = ".",
  [sym_NAME] = "NAME",
  [aux_sym_float_token1] = "float_token1",
  [sym__DIGITS] = "_DIGITS",
  [sym__SIGN] = "_SIGN",
  [anon_sym_STAR] = "*",
  [anon_sym_SLASH] = "/",
  [anon_sym_STAR_STAR] = "**",
  [aux_sym_unit_token1] = "unit_token1",
  [anon_sym_u00b0] = "\u00b0",
  [anon_sym_PERCENT] = "%",
  [anon_sym_COMMA] = ",",
  [anon_sym_PLUS] = "+",
  [anon_sym_DASH] = "-",
  [sym_expression] = "expression",
  [sym__sub_expression] = "_sub_expression",
  [sym_parenthesized_expression] = "parenthesized_expression",
  [sym_variable] = "variable",
  [sym__DOT] = "_DOT",
  [sym__scalar] = "_scalar",
  [sym__number] = "_number",
  [sym_integer] = "integer",
  [sym_float] = "float",
  [sym_quantity] = "quantity",
  [sym_units] = "units",
  [aux_sym__units_mult_part] = "_units_mult_part",
  [aux_sym__units_div_part] = "_units_div_part",
  [sym_unit_term] = "unit_term",
  [sym_unit] = "unit",
  [sym_call] = "call",
  [sym_args] = "args",
  [sym_binary_operator] = "binary_operator",
  [aux_sym_variable_repeat1] = "variable_repeat1",
  [aux_sym_args_repeat1] = "args_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_DOT] = anon_sym_DOT,
  [sym_NAME] = sym_NAME,
  [aux_sym_float_token1] = aux_sym_float_token1,
  [sym__DIGITS] = sym__DIGITS,
  [sym__SIGN] = sym__SIGN,
  [anon_sym_STAR] = anon_sym_STAR,
  [anon_sym_SLASH] = anon_sym_SLASH,
  [anon_sym_STAR_STAR] = anon_sym_STAR_STAR,
  [aux_sym_unit_token1] = aux_sym_unit_token1,
  [anon_sym_u00b0] = anon_sym_u00b0,
  [anon_sym_PERCENT] = anon_sym_PERCENT,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_PLUS] = anon_sym_PLUS,
  [anon_sym_DASH] = anon_sym_DASH,
  [sym_expression] = sym_expression,
  [sym__sub_expression] = sym__sub_expression,
  [sym_parenthesized_expression] = sym_parenthesized_expression,
  [sym_variable] = sym_variable,
  [sym__DOT] = sym__DOT,
  [sym__scalar] = sym__scalar,
  [sym__number] = sym__number,
  [sym_integer] = sym_integer,
  [sym_float] = sym_float,
  [sym_quantity] = sym_quantity,
  [sym_units] = sym_units,
  [aux_sym__units_mult_part] = aux_sym__units_mult_part,
  [aux_sym__units_div_part] = aux_sym__units_div_part,
  [sym_unit_term] = sym_unit_term,
  [sym_unit] = sym_unit,
  [sym_call] = sym_call,
  [sym_args] = sym_args,
  [sym_binary_operator] = sym_binary_operator,
  [aux_sym_variable_repeat1] = aux_sym_variable_repeat1,
  [aux_sym_args_repeat1] = aux_sym_args_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = false,
  },
  [sym_NAME] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_float_token1] = {
    .visible = false,
    .named = false,
  },
  [sym__DIGITS] = {
    .visible = false,
    .named = true,
  },
  [sym__SIGN] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_STAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_STAR_STAR] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_unit_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_u00b0] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PERCENT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PLUS] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = false,
  },
  [sym_expression] = {
    .visible = true,
    .named = true,
  },
  [sym__sub_expression] = {
    .visible = false,
    .named = true,
  },
  [sym_parenthesized_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_variable] = {
    .visible = true,
    .named = true,
  },
  [sym__DOT] = {
    .visible = false,
    .named = true,
  },
  [sym__scalar] = {
    .visible = false,
    .named = true,
  },
  [sym__number] = {
    .visible = false,
    .named = true,
  },
  [sym_integer] = {
    .visible = true,
    .named = true,
  },
  [sym_float] = {
    .visible = true,
    .named = true,
  },
  [sym_quantity] = {
    .visible = true,
    .named = true,
  },
  [sym_units] = {
    .visible = true,
    .named = true,
  },
  [aux_sym__units_mult_part] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__units_div_part] = {
    .visible = false,
    .named = false,
  },
  [sym_unit_term] = {
    .visible = true,
    .named = true,
  },
  [sym_unit] = {
    .visible = true,
    .named = true,
  },
  [sym_call] = {
    .visible = true,
    .named = true,
  },
  [sym_args] = {
    .visible = true,
    .named = true,
  },
  [sym_binary_operator] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_variable_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_args_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_args = 1,
  field_divisive = 2,
  field_exponent = 3,
  field_expression = 4,
  field_first = 5,
  field_function = 6,
  field_left = 7,
  field_magnitude = 8,
  field_multiplicative = 9,
  field_operator = 10,
  field_right = 11,
  field_unit = 12,
  field_units = 13,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_args] = "args",
  [field_divisive] = "divisive",
  [field_exponent] = "exponent",
  [field_expression] = "expression",
  [field_first] = "first",
  [field_function] = "function",
  [field_left] = "left",
  [field_magnitude] = "magnitude",
  [field_multiplicative] = "multiplicative",
  [field_operator] = "operator",
  [field_right] = "right",
  [field_unit] = "unit",
  [field_units] = "units",
};

static const TSFieldMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 2},
  [2] = {.index = 2, .length = 1},
  [3] = {.index = 3, .length = 1},
  [4] = {.index = 4, .length = 1},
  [5] = {.index = 5, .length = 1},
  [6] = {.index = 6, .length = 3},
  [7] = {.index = 9, .length = 2},
  [8] = {.index = 11, .length = 2},
  [9] = {.index = 13, .length = 2},
  [10] = {.index = 15, .length = 3},
  [11] = {.index = 18, .length = 2},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_magnitude, 0},
    {field_units, 1},
  [2] =
    {field_first, 0},
  [3] =
    {field_unit, 0},
  [4] =
    {field_expression, 1},
  [5] =
    {field_function, 0},
  [6] =
    {field_left, 0},
    {field_operator, 1},
    {field_right, 2},
  [9] =
    {field_first, 0},
    {field_multiplicative, 1},
  [11] =
    {field_divisive, 1},
    {field_first, 0},
  [13] =
    {field_args, 2},
    {field_function, 0},
  [15] =
    {field_divisive, 2},
    {field_first, 0},
    {field_multiplicative, 1},
  [18] =
    {field_exponent, 2},
    {field_unit, 0},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(4);
      ADVANCE_MAP(
        '%', 20,
        '(', 5,
        ')', 6,
        '*', 15,
        '+', 22,
        ',', 21,
        '-', 23,
        '.', 7,
        '/', 16,
        0xb0, 19,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(12);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(8);
      END_STATE();
    case 1:
      if (lookahead == '(') ADVANCE(5);
      if (lookahead == ')') ADVANCE(6);
      if (lookahead == '.') ADVANCE(7);
      if (lookahead == '+' ||
          lookahead == '-') ADVANCE(14);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(12);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(9);
      END_STATE();
    case 2:
      if (eof) ADVANCE(4);
      ADVANCE_MAP(
        '%', 20,
        '(', 5,
        ')', 6,
        '*', 15,
        '+', 22,
        ',', 21,
        '-', 23,
        '.', 7,
        '/', 16,
        0xb0, 19,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(2);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(18);
      END_STATE();
    case 3:
      if (eof) ADVANCE(4);
      ADVANCE_MAP(
        '%', 20,
        ')', 6,
        '*', 15,
        '+', 22,
        ',', 21,
        '-', 23,
        '.', 7,
        '/', 16,
        0xb0, 19,
        'E', 11,
        'e', 11,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(3);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(12);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(18);
      END_STATE();
    case 4:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 5:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 6:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 7:
      ACCEPT_TOKEN(anon_sym_DOT);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(sym_NAME);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_') ADVANCE(9);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(8);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(sym_NAME);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(9);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(aux_sym_float_token1);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(aux_sym_float_token1);
      if (lookahead == '+' ||
          lookahead == '-') ADVANCE(10);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(18);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(sym__DIGITS);
      if (lookahead == '_') ADVANCE(13);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(12);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(sym__DIGITS);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(12);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(sym__SIGN);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(anon_sym_STAR);
      if (lookahead == '*') ADVANCE(17);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(anon_sym_SLASH);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_STAR_STAR);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(aux_sym_unit_token1);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(18);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_u00b0);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_PERCENT);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_PLUS);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(anon_sym_DASH);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 1},
  [2] = {.lex_state = 1},
  [3] = {.lex_state = 1},
  [4] = {.lex_state = 1},
  [5] = {.lex_state = 1},
  [6] = {.lex_state = 1},
  [7] = {.lex_state = 2},
  [8] = {.lex_state = 1},
  [9] = {.lex_state = 2},
  [10] = {.lex_state = 2},
  [11] = {.lex_state = 2},
  [12] = {.lex_state = 3},
  [13] = {.lex_state = 3},
  [14] = {.lex_state = 3},
  [15] = {.lex_state = 3},
  [16] = {.lex_state = 2},
  [17] = {.lex_state = 3},
  [18] = {.lex_state = 3},
  [19] = {.lex_state = 3},
  [20] = {.lex_state = 2},
  [21] = {.lex_state = 2},
  [22] = {.lex_state = 2},
  [23] = {.lex_state = 2},
  [24] = {.lex_state = 2},
  [25] = {.lex_state = 2},
  [26] = {.lex_state = 2},
  [27] = {.lex_state = 2},
  [28] = {.lex_state = 2},
  [29] = {.lex_state = 2},
  [30] = {.lex_state = 2},
  [31] = {.lex_state = 2},
  [32] = {.lex_state = 2},
  [33] = {.lex_state = 2},
  [34] = {.lex_state = 2},
  [35] = {.lex_state = 2},
  [36] = {.lex_state = 2},
  [37] = {.lex_state = 2},
  [38] = {.lex_state = 2},
  [39] = {.lex_state = 2},
  [40] = {.lex_state = 2},
  [41] = {.lex_state = 2},
  [42] = {.lex_state = 2},
  [43] = {.lex_state = 2},
  [44] = {.lex_state = 2},
  [45] = {.lex_state = 2},
  [46] = {.lex_state = 2},
  [47] = {.lex_state = 2},
  [48] = {.lex_state = 2},
  [49] = {.lex_state = 2},
  [50] = {.lex_state = 1},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 0},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 0},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 0},
  [59] = {.lex_state = 1},
  [60] = {.lex_state = 0},
  [61] = {.lex_state = 0},
  [62] = {.lex_state = 0},
  [63] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_DOT] = ACTIONS(1),
    [sym_NAME] = ACTIONS(1),
    [sym__DIGITS] = ACTIONS(1),
    [sym__SIGN] = ACTIONS(1),
    [anon_sym_STAR] = ACTIONS(1),
    [anon_sym_SLASH] = ACTIONS(1),
    [anon_sym_STAR_STAR] = ACTIONS(1),
    [aux_sym_unit_token1] = ACTIONS(1),
    [anon_sym_u00b0] = ACTIONS(1),
    [anon_sym_PERCENT] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_PLUS] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
  },
  [1] = {
    [sym_expression] = STATE(62),
    [sym__sub_expression] = STATE(47),
    [sym_parenthesized_expression] = STATE(47),
    [sym_variable] = STATE(47),
    [sym__scalar] = STATE(47),
    [sym__number] = STATE(47),
    [sym_integer] = STATE(47),
    [sym_float] = STATE(10),
    [sym_quantity] = STATE(47),
    [sym_call] = STATE(47),
    [sym_binary_operator] = STATE(47),
    [anon_sym_LPAREN] = ACTIONS(3),
    [anon_sym_DOT] = ACTIONS(5),
    [sym_NAME] = ACTIONS(7),
    [sym__DIGITS] = ACTIONS(9),
    [sym__SIGN] = ACTIONS(11),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 9,
    ACTIONS(3), 1,
      anon_sym_LPAREN,
    ACTIONS(5), 1,
      anon_sym_DOT,
    ACTIONS(7), 1,
      sym_NAME,
    ACTIONS(9), 1,
      sym__DIGITS,
    ACTIONS(11), 1,
      sym__SIGN,
    ACTIONS(13), 1,
      anon_sym_RPAREN,
    STATE(10), 1,
      sym_float,
    STATE(58), 1,
      sym_args,
    STATE(42), 9,
      sym__sub_expression,
      sym_parenthesized_expression,
      sym_variable,
      sym__scalar,
      sym__number,
      sym_integer,
      sym_quantity,
      sym_call,
      sym_binary_operator,
  [36] = 7,
    ACTIONS(3), 1,
      anon_sym_LPAREN,
    ACTIONS(5), 1,
      anon_sym_DOT,
    ACTIONS(7), 1,
      sym_NAME,
    ACTIONS(9), 1,
      sym__DIGITS,
    ACTIONS(11), 1,
      sym__SIGN,
    STATE(10), 1,
      sym_float,
    STATE(46), 9,
      sym__sub_expression,
      sym_parenthesized_expression,
      sym_variable,
      sym__scalar,
      sym__number,
      sym_integer,
      sym_quantity,
      sym_call,
      sym_binary_operator,
  [66] = 7,
    ACTIONS(3), 1,
      anon_sym_LPAREN,
    ACTIONS(5), 1,
      anon_sym_DOT,
    ACTIONS(7), 1,
      sym_NAME,
    ACTIONS(9), 1,
      sym__DIGITS,
    ACTIONS(11), 1,
      sym__SIGN,
    STATE(10), 1,
      sym_float,
    STATE(43), 9,
      sym__sub_expression,
      sym_parenthesized_expression,
      sym_variable,
      sym__scalar,
      sym__number,
      sym_integer,
      sym_quantity,
      sym_call,
      sym_binary_operator,
  [96] = 7,
    ACTIONS(3), 1,
      anon_sym_LPAREN,
    ACTIONS(5), 1,
      anon_sym_DOT,
    ACTIONS(7), 1,
      sym_NAME,
    ACTIONS(9), 1,
      sym__DIGITS,
    ACTIONS(11), 1,
      sym__SIGN,
    STATE(10), 1,
      sym_float,
    STATE(44), 9,
      sym__sub_expression,
      sym_parenthesized_expression,
      sym_variable,
      sym__scalar,
      sym__number,
      sym_integer,
      sym_quantity,
      sym_call,
      sym_binary_operator,
  [126] = 7,
    ACTIONS(3), 1,
      anon_sym_LPAREN,
    ACTIONS(5), 1,
      anon_sym_DOT,
    ACTIONS(7), 1,
      sym_NAME,
    ACTIONS(9), 1,
      sym__DIGITS,
    ACTIONS(11), 1,
      sym__SIGN,
    STATE(10), 1,
      sym_float,
    STATE(36), 9,
      sym__sub_expression,
      sym_parenthesized_expression,
      sym_variable,
      sym__scalar,
      sym__number,
      sym_integer,
      sym_quantity,
      sym_call,
      sym_binary_operator,
  [156] = 7,
    ACTIONS(17), 1,
      anon_sym_STAR,
    ACTIONS(19), 1,
      anon_sym_SLASH,
    STATE(22), 1,
      sym_unit,
    STATE(32), 1,
      aux_sym__units_div_part,
    STATE(9), 2,
      aux_sym__units_mult_part,
      sym_unit_term,
    ACTIONS(21), 3,
      aux_sym_unit_token1,
      anon_sym_u00b0,
      anon_sym_PERCENT,
    ACTIONS(15), 6,
      ts_builtin_sym_end,
      anon_sym_RPAREN,
      anon_sym_STAR_STAR,
      anon_sym_COMMA,
      anon_sym_PLUS,
      anon_sym_DASH,
  [186] = 7,
    ACTIONS(3), 1,
      anon_sym_LPAREN,
    ACTIONS(5), 1,
      anon_sym_DOT,
    ACTIONS(7), 1,
      sym_NAME,
    ACTIONS(9), 1,
      sym__DIGITS,
    ACTIONS(11), 1,
      sym__SIGN,
    STATE(10), 1,
      sym_float,
    STATE(45), 9,
      sym__sub_expression,
      sym_parenthesized_expression,
      sym_variable,
      sym__scalar,
      sym__number,
      sym_integer,
      sym_quantity,
      sym_call,
      sym_binary_operator,
  [216] = 7,
    ACTIONS(17), 1,
      anon_sym_STAR,
    ACTIONS(19), 1,
      anon_sym_SLASH,
    STATE(22), 1,
      sym_unit,
    STATE(35), 1,
      aux_sym__units_div_part,
    STATE(11), 2,
      aux_sym__units_mult_part,
      sym_unit_term,
    ACTIONS(21), 3,
      aux_sym_unit_token1,
      anon_sym_u00b0,
      anon_sym_PERCENT,
    ACTIONS(23), 6,
      ts_builtin_sym_end,
      anon_sym_RPAREN,
      anon_sym_STAR_STAR,
      anon_sym_COMMA,
      anon_sym_PLUS,
      anon_sym_DASH,
  [246] = 6,
    ACTIONS(27), 1,
      anon_sym_STAR,
    STATE(7), 1,
      sym_unit_term,
    STATE(22), 1,
      sym_unit,
    STATE(37), 1,
      sym_units,
    ACTIONS(21), 3,
      aux_sym_unit_token1,
      anon_sym_u00b0,
      anon_sym_PERCENT,
    ACTIONS(25), 7,
      ts_builtin_sym_end,
      anon_sym_RPAREN,
      anon_sym_SLASH,
      anon_sym_STAR_STAR,
      anon_sym_COMMA,
      anon_sym_PLUS,
      anon_sym_DASH,
  [273] = 5,
    ACTIONS(31), 1,
      anon_sym_STAR,
    STATE(22), 1,
      sym_unit,
    STATE(11), 2,
      aux_sym__units_mult_part,
      sym_unit_term,
    ACTIONS(34), 3,
      aux_sym_unit_token1,
      anon_sym_u00b0,
      anon_sym_PERCENT,
    ACTIONS(29), 7,
      ts_builtin_sym_end,
      anon_sym_RPAREN,
      anon_sym_SLASH,
      anon_sym_STAR_STAR,
      anon_sym_COMMA,
      anon_sym_PLUS,
      anon_sym_DASH,
  [298] = 6,
    ACTIONS(39), 1,
      anon_sym_DOT,
    ACTIONS(41), 1,
      aux_sym_float_token1,
    ACTIONS(43), 1,
      anon_sym_STAR,
    ACTIONS(45), 1,
      aux_sym_unit_token1,
    ACTIONS(47), 2,
      anon_sym_u00b0,
      anon_sym_PERCENT,
    ACTIONS(37), 7,
      ts_builtin_sym_end,
      anon_sym_RPAREN,
      anon_sym_SLASH,
      anon_sym_STAR_STAR,
      anon_sym_COMMA,
      anon_sym_PLUS,
      anon_sym_DASH,
  [324] = 4,
    ACTIONS(51), 1,
      aux_sym_float_token1,
    ACTIONS(53), 1,
      sym__DIGITS,
    ACTIONS(55), 2,
      anon_sym_STAR,
      aux_sym_unit_token1,
    ACTIONS(49), 9,
      ts_builtin_sym_end,
      anon_sym_RPAREN,
      anon_sym_SLASH,
      anon_sym_STAR_STAR,
      anon_sym_u00b0,
      anon_sym_PERCENT,
      anon_sym_COMMA,
      anon_sym_PLUS,
      anon_sym_DASH,
  [346] = 6,
    ACTIONS(51), 1,
      aux_sym_float_token1,
    ACTIONS(55), 1,
      aux_sym_unit_token1,
    ACTIONS(59), 1,
      anon_sym_DOT,
    ACTIONS(61), 1,
      anon_sym_STAR,
    ACTIONS(49), 2,
      anon_sym_u00b0,
      anon_sym_PERCENT,
    ACTIONS(57), 7,
      ts_builtin_sym_end,
      anon_sym_RPAREN,
      anon_sym_SLASH,
      anon_sym_STAR_STAR,
      anon_sym_COMMA,
      anon_sym_PLUS,
      anon_sym_DASH,
  [372] = 4,
    ACTIONS(65), 1,
      aux_sym_float_token1,
    ACTIONS(67), 1,
      sym__DIGITS,
    ACTIONS(69), 2,
      anon_sym_STAR,
      aux_sym_unit_token1,
    ACTIONS(63), 9,
      ts_builtin_sym_end,
      anon_sym_RPAREN,
      anon_sym_SLASH,
      anon_sym_STAR_STAR,
      anon_sym_u00b0,
      anon_sym_PERCENT,
      anon_sym_COMMA,
      anon_sym_PLUS,
      anon_sym_DASH,
  [394] = 6,
    ACTIONS(73), 1,
      anon_sym_LPAREN,
    ACTIONS(75), 1,
      anon_sym_DOT,
    ACTIONS(77), 1,
      anon_sym_STAR,
    STATE(24), 1,
      aux_sym_variable_repeat1,
    STATE(59), 1,
      sym__DOT,
    ACTIONS(71), 7,
      ts_builtin_sym_end,
      anon_sym_RPAREN,
      anon_sym_SLASH,
      anon_sym_STAR_STAR,
      anon_sym_COMMA,
      anon_sym_PLUS,
      anon_sym_DASH,
  [419] = 3,
    ACTIONS(51), 1,
      aux_sym_float_token1,
    ACTIONS(55), 2,
      anon_sym_STAR,
      aux_sym_unit_token1,
    ACTIONS(49), 9,
      ts_builtin_sym_end,
      anon_sym_RPAREN,
      anon_sym_SLASH,
      anon_sym_STAR_STAR,
      anon_sym_u00b0,
      anon_sym_PERCENT,
      anon_sym_COMMA,
      anon_sym_PLUS,
      anon_sym_DASH,
  [438] = 3,
    ACTIONS(81), 1,
      aux_sym_float_token1,
    ACTIONS(83), 2,
      anon_sym_STAR,
      aux_sym_unit_token1,
    ACTIONS(79), 9,
      ts_builtin_sym_end,
      anon_sym_RPAREN,
      anon_sym_SLASH,
      anon_sym_STAR_STAR,
      anon_sym_u00b0,
      anon_sym_PERCENT,
      anon_sym_COMMA,
      anon_sym_PLUS,
      anon_sym_DASH,
  [457] = 3,
    ACTIONS(65), 1,
      aux_sym_float_token1,
    ACTIONS(69), 2,
      anon_sym_STAR,
      aux_sym_unit_token1,
    ACTIONS(63), 9,
      ts_builtin_sym_end,
      anon_sym_RPAREN,
      anon_sym_SLASH,
      anon_sym_STAR_STAR,
      anon_sym_u00b0,
      anon_sym_PERCENT,
      anon_sym_COMMA,
      anon_sym_PLUS,
      anon_sym_DASH,
  [476] = 2,
    ACTIONS(87), 1,
      anon_sym_STAR,
    ACTIONS(85), 10,
      ts_builtin_sym_end,
      anon_sym_RPAREN,
      anon_sym_SLASH,
      anon_sym_STAR_STAR,
      aux_sym_unit_token1,
      anon_sym_u00b0,
      anon_sym_PERCENT,
      anon_sym_COMMA,
      anon_sym_PLUS,
      anon_sym_DASH,
  [492] = 2,
    ACTIONS(91), 1,
      anon_sym_STAR,
    ACTIONS(89), 10,
      ts_builtin_sym_end,
      anon_sym_RPAREN,
      anon_sym_SLASH,
      anon_sym_STAR_STAR,
      aux_sym_unit_token1,
      anon_sym_u00b0,
      anon_sym_PERCENT,
      anon_sym_COMMA,
      anon_sym_PLUS,
      anon_sym_DASH,
  [508] = 3,
    ACTIONS(95), 1,
      anon_sym_STAR,
    ACTIONS(97), 1,
      anon_sym_STAR_STAR,
    ACTIONS(93), 9,
      ts_builtin_sym_end,
      anon_sym_RPAREN,
      anon_sym_SLASH,
      aux_sym_unit_token1,
      anon_sym_u00b0,
      anon_sym_PERCENT,
      anon_sym_COMMA,
      anon_sym_PLUS,
      anon_sym_DASH,
  [526] = 5,
    ACTIONS(101), 1,
      anon_sym_DOT,
    ACTIONS(104), 1,
      anon_sym_STAR,
    STATE(23), 1,
      aux_sym_variable_repeat1,
    STATE(59), 1,
      sym__DOT,
    ACTIONS(99), 7,
      ts_builtin_sym_end,
      anon_sym_RPAREN,
      anon_sym_SLASH,
      anon_sym_STAR_STAR,
      anon_sym_COMMA,
      anon_sym_PLUS,
      anon_sym_DASH,
  [548] = 5,
    ACTIONS(75), 1,
      anon_sym_DOT,
    ACTIONS(108), 1,
      anon_sym_STAR,
    STATE(23), 1,
      aux_sym_variable_repeat1,
    STATE(59), 1,
      sym__DOT,
    ACTIONS(106), 7,
      ts_builtin_sym_end,
      anon_sym_RPAREN,
      anon_sym_SLASH,
      anon_sym_STAR_STAR,
      anon_sym_COMMA,
      anon_sym_PLUS,
      anon_sym_DASH,
  [570] = 2,
    ACTIONS(69), 1,
      anon_sym_STAR,
    ACTIONS(63), 10,
      ts_builtin_sym_end,
      anon_sym_RPAREN,
      anon_sym_SLASH,
      anon_sym_STAR_STAR,
      aux_sym_unit_token1,
      anon_sym_u00b0,
      anon_sym_PERCENT,
      anon_sym_COMMA,
      anon_sym_PLUS,
      anon_sym_DASH,
  [586] = 2,
    ACTIONS(112), 1,
      anon_sym_STAR,
    ACTIONS(110), 10,
      ts_builtin_sym_end,
      anon_sym_RPAREN,
      anon_sym_SLASH,
      anon_sym_STAR_STAR,
      aux_sym_unit_token1,
      anon_sym_u00b0,
      anon_sym_PERCENT,
      anon_sym_COMMA,
      anon_sym_PLUS,
      anon_sym_DASH,
  [602] = 2,
    ACTIONS(83), 1,
      anon_sym_STAR,
    ACTIONS(79), 10,
      ts_builtin_sym_end,
      anon_sym_RPAREN,
      anon_sym_SLASH,
      anon_sym_STAR_STAR,
      aux_sym_unit_token1,
      anon_sym_u00b0,
      anon_sym_PERCENT,
      anon_sym_COMMA,
      anon_sym_PLUS,
      anon_sym_DASH,
  [618] = 2,
    ACTIONS(114), 1,
      anon_sym_STAR,
    ACTIONS(29), 10,
      ts_builtin_sym_end,
      anon_sym_RPAREN,
      anon_sym_SLASH,
      anon_sym_STAR_STAR,
      aux_sym_unit_token1,
      anon_sym_u00b0,
      anon_sym_PERCENT,
      anon_sym_COMMA,
      anon_sym_PLUS,
      anon_sym_DASH,
  [634] = 2,
    ACTIONS(43), 1,
      anon_sym_STAR,
    ACTIONS(37), 10,
      ts_builtin_sym_end,
      anon_sym_RPAREN,
      anon_sym_SLASH,
      anon_sym_STAR_STAR,
      aux_sym_unit_token1,
      anon_sym_u00b0,
      anon_sym_PERCENT,
      anon_sym_COMMA,
      anon_sym_PLUS,
      anon_sym_DASH,
  [650] = 2,
    ACTIONS(118), 1,
      anon_sym_STAR,
    ACTIONS(116), 10,
      ts_builtin_sym_end,
      anon_sym_RPAREN,
      anon_sym_SLASH,
      anon_sym_STAR_STAR,
      aux_sym_unit_token1,
      anon_sym_u00b0,
      anon_sym_PERCENT,
      anon_sym_COMMA,
      anon_sym_PLUS,
      anon_sym_DASH,
  [666] = 2,
    ACTIONS(61), 1,
      anon_sym_STAR,
    ACTIONS(57), 10,
      ts_builtin_sym_end,
      anon_sym_RPAREN,
      anon_sym_SLASH,
      anon_sym_STAR_STAR,
      aux_sym_unit_token1,
      anon_sym_u00b0,
      anon_sym_PERCENT,
      anon_sym_COMMA,
      anon_sym_PLUS,
      anon_sym_DASH,
  [682] = 4,
    ACTIONS(19), 1,
      anon_sym_SLASH,
    ACTIONS(122), 1,
      anon_sym_STAR,
    STATE(34), 1,
      aux_sym__units_div_part,
    ACTIONS(120), 6,
      ts_builtin_sym_end,
      anon_sym_RPAREN,
      anon_sym_STAR_STAR,
      anon_sym_COMMA,
      anon_sym_PLUS,
      anon_sym_DASH,
  [700] = 2,
    ACTIONS(104), 1,
      anon_sym_STAR,
    ACTIONS(99), 8,
      ts_builtin_sym_end,
      anon_sym_RPAREN,
      anon_sym_DOT,
      anon_sym_SLASH,
      anon_sym_STAR_STAR,
      anon_sym_COMMA,
      anon_sym_PLUS,
      anon_sym_DASH,
  [714] = 4,
    ACTIONS(126), 1,
      anon_sym_STAR,
    ACTIONS(128), 1,
      anon_sym_SLASH,
    STATE(34), 1,
      aux_sym__units_div_part,
    ACTIONS(124), 6,
      ts_builtin_sym_end,
      anon_sym_RPAREN,
      anon_sym_STAR_STAR,
      anon_sym_COMMA,
      anon_sym_PLUS,
      anon_sym_DASH,
  [732] = 4,
    ACTIONS(19), 1,
      anon_sym_SLASH,
    ACTIONS(133), 1,
      anon_sym_STAR,
    STATE(34), 1,
      aux_sym__units_div_part,
    ACTIONS(131), 6,
      ts_builtin_sym_end,
      anon_sym_RPAREN,
      anon_sym_STAR_STAR,
      anon_sym_COMMA,
      anon_sym_PLUS,
      anon_sym_DASH,
  [750] = 4,
    ACTIONS(137), 1,
      anon_sym_STAR,
    ACTIONS(139), 1,
      anon_sym_SLASH,
    ACTIONS(141), 1,
      anon_sym_STAR_STAR,
    ACTIONS(135), 5,
      ts_builtin_sym_end,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_PLUS,
      anon_sym_DASH,
  [767] = 2,
    ACTIONS(145), 1,
      anon_sym_STAR,
    ACTIONS(143), 7,
      ts_builtin_sym_end,
      anon_sym_RPAREN,
      anon_sym_SLASH,
      anon_sym_STAR_STAR,
      anon_sym_COMMA,
      anon_sym_PLUS,
      anon_sym_DASH,
  [780] = 2,
    ACTIONS(149), 1,
      anon_sym_STAR,
    ACTIONS(147), 7,
      ts_builtin_sym_end,
      anon_sym_RPAREN,
      anon_sym_SLASH,
      anon_sym_STAR_STAR,
      anon_sym_COMMA,
      anon_sym_PLUS,
      anon_sym_DASH,
  [793] = 2,
    ACTIONS(153), 1,
      anon_sym_STAR,
    ACTIONS(151), 7,
      ts_builtin_sym_end,
      anon_sym_RPAREN,
      anon_sym_SLASH,
      anon_sym_STAR_STAR,
      anon_sym_COMMA,
      anon_sym_PLUS,
      anon_sym_DASH,
  [806] = 2,
    ACTIONS(157), 1,
      anon_sym_STAR,
    ACTIONS(155), 7,
      ts_builtin_sym_end,
      anon_sym_RPAREN,
      anon_sym_SLASH,
      anon_sym_STAR_STAR,
      anon_sym_COMMA,
      anon_sym_PLUS,
      anon_sym_DASH,
  [819] = 2,
    ACTIONS(126), 1,
      anon_sym_STAR,
    ACTIONS(124), 7,
      ts_builtin_sym_end,
      anon_sym_RPAREN,
      anon_sym_SLASH,
      anon_sym_STAR_STAR,
      anon_sym_COMMA,
      anon_sym_PLUS,
      anon_sym_DASH,
  [832] = 7,
    ACTIONS(137), 1,
      anon_sym_STAR,
    ACTIONS(139), 1,
      anon_sym_SLASH,
    ACTIONS(141), 1,
      anon_sym_STAR_STAR,
    ACTIONS(159), 1,
      anon_sym_RPAREN,
    ACTIONS(161), 1,
      anon_sym_COMMA,
    STATE(51), 1,
      aux_sym_args_repeat1,
    ACTIONS(163), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
  [855] = 3,
    ACTIONS(141), 1,
      anon_sym_STAR_STAR,
    ACTIONS(165), 1,
      anon_sym_STAR,
    ACTIONS(135), 6,
      ts_builtin_sym_end,
      anon_sym_RPAREN,
      anon_sym_SLASH,
      anon_sym_COMMA,
      anon_sym_PLUS,
      anon_sym_DASH,
  [870] = 3,
    ACTIONS(141), 1,
      anon_sym_STAR_STAR,
    ACTIONS(165), 1,
      anon_sym_STAR,
    ACTIONS(135), 6,
      ts_builtin_sym_end,
      anon_sym_RPAREN,
      anon_sym_SLASH,
      anon_sym_COMMA,
      anon_sym_PLUS,
      anon_sym_DASH,
  [885] = 5,
    ACTIONS(137), 1,
      anon_sym_STAR,
    ACTIONS(139), 1,
      anon_sym_SLASH,
    ACTIONS(141), 1,
      anon_sym_STAR_STAR,
    ACTIONS(163), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(167), 2,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [903] = 5,
    ACTIONS(137), 1,
      anon_sym_STAR,
    ACTIONS(139), 1,
      anon_sym_SLASH,
    ACTIONS(141), 1,
      anon_sym_STAR_STAR,
    ACTIONS(169), 1,
      anon_sym_RPAREN,
    ACTIONS(163), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
  [920] = 5,
    ACTIONS(137), 1,
      anon_sym_STAR,
    ACTIONS(139), 1,
      anon_sym_SLASH,
    ACTIONS(141), 1,
      anon_sym_STAR_STAR,
    ACTIONS(171), 1,
      ts_builtin_sym_end,
    ACTIONS(163), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
  [937] = 3,
    STATE(22), 1,
      sym_unit,
    STATE(28), 1,
      sym_unit_term,
    ACTIONS(21), 3,
      aux_sym_unit_token1,
      anon_sym_u00b0,
      anon_sym_PERCENT,
  [949] = 3,
    STATE(22), 1,
      sym_unit,
    STATE(41), 1,
      sym_unit_term,
    ACTIONS(21), 3,
      aux_sym_unit_token1,
      anon_sym_u00b0,
      anon_sym_PERCENT,
  [961] = 3,
    ACTIONS(173), 1,
      sym__DIGITS,
    ACTIONS(175), 1,
      sym__SIGN,
    STATE(30), 1,
      sym_integer,
  [971] = 3,
    ACTIONS(161), 1,
      anon_sym_COMMA,
    ACTIONS(177), 1,
      anon_sym_RPAREN,
    STATE(52), 1,
      aux_sym_args_repeat1,
  [981] = 3,
    ACTIONS(167), 1,
      anon_sym_RPAREN,
    ACTIONS(179), 1,
      anon_sym_COMMA,
    STATE(52), 1,
      aux_sym_args_repeat1,
  [991] = 2,
    ACTIONS(182), 1,
      anon_sym_DOT,
    ACTIONS(184), 1,
      sym__DIGITS,
  [998] = 1,
    ACTIONS(186), 1,
      sym__DIGITS,
  [1002] = 1,
    ACTIONS(188), 1,
      sym__DIGITS,
  [1006] = 1,
    ACTIONS(190), 1,
      sym__DIGITS,
  [1010] = 1,
    ACTIONS(192), 1,
      sym__DIGITS,
  [1014] = 1,
    ACTIONS(194), 1,
      anon_sym_RPAREN,
  [1018] = 1,
    ACTIONS(196), 1,
      sym_NAME,
  [1022] = 1,
    ACTIONS(53), 1,
      sym__DIGITS,
  [1026] = 1,
    ACTIONS(198), 1,
      sym__DIGITS,
  [1030] = 1,
    ACTIONS(200), 1,
      ts_builtin_sym_end,
  [1034] = 1,
    ACTIONS(202), 1,
      sym__DIGITS,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 36,
  [SMALL_STATE(4)] = 66,
  [SMALL_STATE(5)] = 96,
  [SMALL_STATE(6)] = 126,
  [SMALL_STATE(7)] = 156,
  [SMALL_STATE(8)] = 186,
  [SMALL_STATE(9)] = 216,
  [SMALL_STATE(10)] = 246,
  [SMALL_STATE(11)] = 273,
  [SMALL_STATE(12)] = 298,
  [SMALL_STATE(13)] = 324,
  [SMALL_STATE(14)] = 346,
  [SMALL_STATE(15)] = 372,
  [SMALL_STATE(16)] = 394,
  [SMALL_STATE(17)] = 419,
  [SMALL_STATE(18)] = 438,
  [SMALL_STATE(19)] = 457,
  [SMALL_STATE(20)] = 476,
  [SMALL_STATE(21)] = 492,
  [SMALL_STATE(22)] = 508,
  [SMALL_STATE(23)] = 526,
  [SMALL_STATE(24)] = 548,
  [SMALL_STATE(25)] = 570,
  [SMALL_STATE(26)] = 586,
  [SMALL_STATE(27)] = 602,
  [SMALL_STATE(28)] = 618,
  [SMALL_STATE(29)] = 634,
  [SMALL_STATE(30)] = 650,
  [SMALL_STATE(31)] = 666,
  [SMALL_STATE(32)] = 682,
  [SMALL_STATE(33)] = 700,
  [SMALL_STATE(34)] = 714,
  [SMALL_STATE(35)] = 732,
  [SMALL_STATE(36)] = 750,
  [SMALL_STATE(37)] = 767,
  [SMALL_STATE(38)] = 780,
  [SMALL_STATE(39)] = 793,
  [SMALL_STATE(40)] = 806,
  [SMALL_STATE(41)] = 819,
  [SMALL_STATE(42)] = 832,
  [SMALL_STATE(43)] = 855,
  [SMALL_STATE(44)] = 870,
  [SMALL_STATE(45)] = 885,
  [SMALL_STATE(46)] = 903,
  [SMALL_STATE(47)] = 920,
  [SMALL_STATE(48)] = 937,
  [SMALL_STATE(49)] = 949,
  [SMALL_STATE(50)] = 961,
  [SMALL_STATE(51)] = 971,
  [SMALL_STATE(52)] = 981,
  [SMALL_STATE(53)] = 991,
  [SMALL_STATE(54)] = 998,
  [SMALL_STATE(55)] = 1002,
  [SMALL_STATE(56)] = 1006,
  [SMALL_STATE(57)] = 1010,
  [SMALL_STATE(58)] = 1014,
  [SMALL_STATE(59)] = 1018,
  [SMALL_STATE(60)] = 1022,
  [SMALL_STATE(61)] = 1026,
  [SMALL_STATE(62)] = 1030,
  [SMALL_STATE(63)] = 1034,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [15] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_units, 1, 0, 2),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(48),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [23] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_units, 2, 0, 7),
  [25] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__number, 1, 0, 0),
  [27] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__number, 1, 0, 0),
  [29] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__units_mult_part, 2, 0, 0),
  [31] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__units_mult_part, 2, 0, 0), SHIFT_REPEAT(48),
  [34] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__units_mult_part, 2, 0, 0), SHIFT_REPEAT(26),
  [37] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_integer, 1, 0, 0),
  [39] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [41] = {.entry = {.count = 1, .reusable = false}}, SHIFT(54),
  [43] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_integer, 1, 0, 0),
  [45] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_float, 1, 0, 0),
  [47] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_float, 1, 0, 0),
  [49] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_float, 2, 0, 0),
  [51] = {.entry = {.count = 1, .reusable = false}}, SHIFT(63),
  [53] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [55] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_float, 2, 0, 0),
  [57] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_integer, 2, 0, 0),
  [59] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [61] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_integer, 2, 0, 0),
  [63] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_float, 3, 0, 0),
  [65] = {.entry = {.count = 1, .reusable = false}}, SHIFT(55),
  [67] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [69] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_float, 3, 0, 0),
  [71] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_variable, 1, 0, 0),
  [73] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [75] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [77] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_variable, 1, 0, 0),
  [79] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_float, 4, 0, 0),
  [81] = {.entry = {.count = 1, .reusable = false}}, SHIFT(61),
  [83] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_float, 4, 0, 0),
  [85] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_float, 5, 0, 0),
  [87] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_float, 5, 0, 0),
  [89] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_float, 6, 0, 0),
  [91] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_float, 6, 0, 0),
  [93] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_unit_term, 1, 0, 3),
  [95] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_unit_term, 1, 0, 3),
  [97] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [99] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_variable_repeat1, 2, 0, 0),
  [101] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_variable_repeat1, 2, 0, 0), SHIFT_REPEAT(59),
  [104] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_variable_repeat1, 2, 0, 0),
  [106] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_variable, 2, 0, 0),
  [108] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_variable, 2, 0, 0),
  [110] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_unit, 1, 0, 0),
  [112] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_unit, 1, 0, 0),
  [114] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym__units_mult_part, 2, 0, 0),
  [116] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_unit_term, 3, 0, 11),
  [118] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_unit_term, 3, 0, 11),
  [120] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_units, 2, 0, 8),
  [122] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_units, 2, 0, 8),
  [124] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__units_div_part, 2, 0, 0),
  [126] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym__units_div_part, 2, 0, 0),
  [128] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__units_div_part, 2, 0, 0), SHIFT_REPEAT(49),
  [131] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_units, 3, 0, 10),
  [133] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_units, 3, 0, 10),
  [135] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_binary_operator, 3, 0, 6),
  [137] = {.entry = {.count = 1, .reusable = false}}, SHIFT(4),
  [139] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [141] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [143] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_quantity, 2, 0, 1),
  [145] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_quantity, 2, 0, 1),
  [147] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_call, 4, 0, 9),
  [149] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_call, 4, 0, 9),
  [151] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parenthesized_expression, 3, 0, 4),
  [153] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_parenthesized_expression, 3, 0, 4),
  [155] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_call, 3, 0, 5),
  [157] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_call, 3, 0, 5),
  [159] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_args, 1, 0, 0),
  [161] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [163] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [165] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_binary_operator, 3, 0, 6),
  [167] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_args_repeat1, 2, 0, 0),
  [169] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [171] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression, 1, 0, 0),
  [173] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [175] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [177] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_args, 2, 0, 0),
  [179] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_args_repeat1, 2, 0, 0), SHIFT_REPEAT(8),
  [182] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [184] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [186] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [188] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [190] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [192] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [194] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [196] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [198] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [200] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [202] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_caqtus(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
