#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 59
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 37
#define ALIAS_COUNT 0
#define TOKEN_COUNT 18
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 12
#define MAX_ALIAS_SEQUENCE_LENGTH 6
#define PRODUCTION_ID_COUNT 11

enum ts_symbol_identifiers {
  anon_sym_DOT = 1,
  sym_NAME = 2,
  aux_sym_float_token1 = 3,
  sym__DIGITS = 4,
  sym__SIGN = 5,
  anon_sym_STAR = 6,
  anon_sym_SLASH = 7,
  anon_sym_CARET = 8,
  anon_sym_STAR_STAR = 9,
  aux_sym_unit_token1 = 10,
  anon_sym_u00b0 = 11,
  anon_sym_PERCENT = 12,
  anon_sym_LPAREN = 13,
  anon_sym_RPAREN = 14,
  anon_sym_COMMA = 15,
  anon_sym_PLUS = 16,
  anon_sym_DASH = 17,
  sym_expression = 18,
  sym__sub_expression = 19,
  sym_variable = 20,
  sym__DOT = 21,
  sym__scalar = 22,
  sym__number = 23,
  sym_integer = 24,
  sym_float = 25,
  sym_quantity = 26,
  sym_units = 27,
  aux_sym__units_mult_part = 28,
  aux_sym__units_div_part = 29,
  sym_unit_term = 30,
  sym_unit = 31,
  sym_call = 32,
  sym_args = 33,
  sym_binary_operator = 34,
  aux_sym_variable_repeat1 = 35,
  aux_sym_args_repeat1 = 36,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_DOT] = ".",
  [sym_NAME] = "NAME",
  [aux_sym_float_token1] = "float_token1",
  [sym__DIGITS] = "_DIGITS",
  [sym__SIGN] = "_SIGN",
  [anon_sym_STAR] = "*",
  [anon_sym_SLASH] = "/",
  [anon_sym_CARET] = "^",
  [anon_sym_STAR_STAR] = "**",
  [aux_sym_unit_token1] = "unit_token1",
  [anon_sym_u00b0] = "\u00b0",
  [anon_sym_PERCENT] = "%",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_COMMA] = ",",
  [anon_sym_PLUS] = "+",
  [anon_sym_DASH] = "-",
  [sym_expression] = "expression",
  [sym__sub_expression] = "_sub_expression",
  [sym_variable] = "variable",
  [sym__DOT] = "_DOT",
  [sym__scalar] = "_scalar",
  [sym__number] = "_number",
  [sym_integer] = "integer",
  [sym_float] = "float",
  [sym_quantity] = "quantity",
  [sym_units] = "units",
  [aux_sym__units_mult_part] = "_units_mult_part",
  [aux_sym__units_div_part] = "_units_div_part",
  [sym_unit_term] = "unit_term",
  [sym_unit] = "unit",
  [sym_call] = "call",
  [sym_args] = "args",
  [sym_binary_operator] = "binary_operator",
  [aux_sym_variable_repeat1] = "variable_repeat1",
  [aux_sym_args_repeat1] = "args_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_DOT] = anon_sym_DOT,
  [sym_NAME] = sym_NAME,
  [aux_sym_float_token1] = aux_sym_float_token1,
  [sym__DIGITS] = sym__DIGITS,
  [sym__SIGN] = sym__SIGN,
  [anon_sym_STAR] = anon_sym_STAR,
  [anon_sym_SLASH] = anon_sym_SLASH,
  [anon_sym_CARET] = anon_sym_CARET,
  [anon_sym_STAR_STAR] = anon_sym_STAR_STAR,
  [aux_sym_unit_token1] = aux_sym_unit_token1,
  [anon_sym_u00b0] = anon_sym_u00b0,
  [anon_sym_PERCENT] = anon_sym_PERCENT,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_PLUS] = anon_sym_PLUS,
  [anon_sym_DASH] = anon_sym_DASH,
  [sym_expression] = sym_expression,
  [sym__sub_expression] = sym__sub_expression,
  [sym_variable] = sym_variable,
  [sym__DOT] = sym__DOT,
  [sym__scalar] = sym__scalar,
  [sym__number] = sym__number,
  [sym_integer] = sym_integer,
  [sym_float] = sym_float,
  [sym_quantity] = sym_quantity,
  [sym_units] = sym_units,
  [aux_sym__units_mult_part] = aux_sym__units_mult_part,
  [aux_sym__units_div_part] = aux_sym__units_div_part,
  [sym_unit_term] = sym_unit_term,
  [sym_unit] = sym_unit,
  [sym_call] = sym_call,
  [sym_args] = sym_args,
  [sym_binary_operator] = sym_binary_operator,
  [aux_sym_variable_repeat1] = aux_sym_variable_repeat1,
  [aux_sym_args_repeat1] = aux_sym_args_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = false,
  },
  [sym_NAME] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_float_token1] = {
    .visible = false,
    .named = false,
  },
  [sym__DIGITS] = {
    .visible = false,
    .named = true,
  },
  [sym__SIGN] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_STAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_CARET] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_STAR_STAR] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_unit_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_u00b0] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PERCENT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PLUS] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = false,
  },
  [sym_expression] = {
    .visible = true,
    .named = true,
  },
  [sym__sub_expression] = {
    .visible = false,
    .named = true,
  },
  [sym_variable] = {
    .visible = true,
    .named = true,
  },
  [sym__DOT] = {
    .visible = false,
    .named = true,
  },
  [sym__scalar] = {
    .visible = false,
    .named = true,
  },
  [sym__number] = {
    .visible = false,
    .named = true,
  },
  [sym_integer] = {
    .visible = true,
    .named = true,
  },
  [sym_float] = {
    .visible = true,
    .named = true,
  },
  [sym_quantity] = {
    .visible = true,
    .named = true,
  },
  [sym_units] = {
    .visible = true,
    .named = true,
  },
  [aux_sym__units_mult_part] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__units_div_part] = {
    .visible = false,
    .named = false,
  },
  [sym_unit_term] = {
    .visible = true,
    .named = true,
  },
  [sym_unit] = {
    .visible = true,
    .named = true,
  },
  [sym_call] = {
    .visible = true,
    .named = true,
  },
  [sym_args] = {
    .visible = true,
    .named = true,
  },
  [sym_binary_operator] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_variable_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_args_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_args = 1,
  field_divisive = 2,
  field_exponent = 3,
  field_first = 4,
  field_function = 5,
  field_left = 6,
  field_magnitude = 7,
  field_multiplicative = 8,
  field_operator = 9,
  field_right = 10,
  field_unit = 11,
  field_units = 12,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_args] = "args",
  [field_divisive] = "divisive",
  [field_exponent] = "exponent",
  [field_first] = "first",
  [field_function] = "function",
  [field_left] = "left",
  [field_magnitude] = "magnitude",
  [field_multiplicative] = "multiplicative",
  [field_operator] = "operator",
  [field_right] = "right",
  [field_unit] = "unit",
  [field_units] = "units",
};

static const TSFieldMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 2},
  [2] = {.index = 2, .length = 1},
  [3] = {.index = 3, .length = 1},
  [4] = {.index = 4, .length = 1},
  [5] = {.index = 5, .length = 3},
  [6] = {.index = 8, .length = 2},
  [7] = {.index = 10, .length = 2},
  [8] = {.index = 12, .length = 2},
  [9] = {.index = 14, .length = 3},
  [10] = {.index = 17, .length = 2},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_magnitude, 0},
    {field_units, 1},
  [2] =
    {field_first, 0},
  [3] =
    {field_unit, 0},
  [4] =
    {field_function, 0},
  [5] =
    {field_left, 0},
    {field_operator, 1},
    {field_right, 2},
  [8] =
    {field_first, 0},
    {field_multiplicative, 1},
  [10] =
    {field_divisive, 1},
    {field_first, 0},
  [12] =
    {field_args, 2},
    {field_function, 0},
  [14] =
    {field_divisive, 2},
    {field_first, 0},
    {field_multiplicative, 1},
  [17] =
    {field_exponent, 2},
    {field_unit, 0},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(4);
      ADVANCE_MAP(
        '%', 20,
        '(', 21,
        ')', 22,
        '*', 14,
        '+', 24,
        ',', 23,
        '-', 25,
        '.', 5,
        '/', 15,
        '^', 16,
        0xb0, 19,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(10);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(6);
      END_STATE();
    case 1:
      if (lookahead == ')') ADVANCE(22);
      if (lookahead == '.') ADVANCE(5);
      if (lookahead == '+' ||
          lookahead == '-') ADVANCE(12);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(10);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(7);
      END_STATE();
    case 2:
      if (eof) ADVANCE(4);
      ADVANCE_MAP(
        '%', 20,
        '(', 21,
        ')', 22,
        '*', 14,
        '+', 24,
        ',', 23,
        '-', 25,
        '.', 5,
        '/', 15,
        '^', 16,
        0xb0, 19,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(2);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(18);
      END_STATE();
    case 3:
      if (eof) ADVANCE(4);
      ADVANCE_MAP(
        '%', 20,
        ')', 22,
        '*', 13,
        '+', 24,
        ',', 23,
        '-', 25,
        '.', 5,
        '/', 15,
        0xb0, 19,
        'E', 9,
        'e', 9,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(3);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(10);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(18);
      END_STATE();
    case 4:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 5:
      ACCEPT_TOKEN(anon_sym_DOT);
      END_STATE();
    case 6:
      ACCEPT_TOKEN(sym_NAME);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_') ADVANCE(7);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(6);
      END_STATE();
    case 7:
      ACCEPT_TOKEN(sym_NAME);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(7);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(aux_sym_float_token1);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(aux_sym_float_token1);
      if (lookahead == '+' ||
          lookahead == '-') ADVANCE(8);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(18);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(sym__DIGITS);
      if (lookahead == '_') ADVANCE(11);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(10);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(sym__DIGITS);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(10);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(sym__SIGN);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(anon_sym_STAR);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(anon_sym_STAR);
      if (lookahead == '*') ADVANCE(17);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(anon_sym_SLASH);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(anon_sym_CARET);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_STAR_STAR);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(aux_sym_unit_token1);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(18);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_u00b0);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_PERCENT);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_PLUS);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(anon_sym_DASH);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 1},
  [2] = {.lex_state = 1},
  [3] = {.lex_state = 2},
  [4] = {.lex_state = 2},
  [5] = {.lex_state = 2},
  [6] = {.lex_state = 1},
  [7] = {.lex_state = 1},
  [8] = {.lex_state = 1},
  [9] = {.lex_state = 2},
  [10] = {.lex_state = 3},
  [11] = {.lex_state = 3},
  [12] = {.lex_state = 3},
  [13] = {.lex_state = 2},
  [14] = {.lex_state = 2},
  [15] = {.lex_state = 3},
  [16] = {.lex_state = 2},
  [17] = {.lex_state = 3},
  [18] = {.lex_state = 3},
  [19] = {.lex_state = 3},
  [20] = {.lex_state = 2},
  [21] = {.lex_state = 2},
  [22] = {.lex_state = 2},
  [23] = {.lex_state = 2},
  [24] = {.lex_state = 2},
  [25] = {.lex_state = 2},
  [26] = {.lex_state = 2},
  [27] = {.lex_state = 2},
  [28] = {.lex_state = 2},
  [29] = {.lex_state = 2},
  [30] = {.lex_state = 2},
  [31] = {.lex_state = 2},
  [32] = {.lex_state = 2},
  [33] = {.lex_state = 2},
  [34] = {.lex_state = 2},
  [35] = {.lex_state = 2},
  [36] = {.lex_state = 2},
  [37] = {.lex_state = 2},
  [38] = {.lex_state = 2},
  [39] = {.lex_state = 2},
  [40] = {.lex_state = 2},
  [41] = {.lex_state = 2},
  [42] = {.lex_state = 2},
  [43] = {.lex_state = 2},
  [44] = {.lex_state = 2},
  [45] = {.lex_state = 1},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 0},
  [51] = {.lex_state = 1},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 0},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 0},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_DOT] = ACTIONS(1),
    [sym_NAME] = ACTIONS(1),
    [sym__DIGITS] = ACTIONS(1),
    [sym__SIGN] = ACTIONS(1),
    [anon_sym_STAR] = ACTIONS(1),
    [anon_sym_SLASH] = ACTIONS(1),
    [anon_sym_CARET] = ACTIONS(1),
    [anon_sym_STAR_STAR] = ACTIONS(1),
    [aux_sym_unit_token1] = ACTIONS(1),
    [anon_sym_u00b0] = ACTIONS(1),
    [anon_sym_PERCENT] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_PLUS] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
  },
  [1] = {
    [sym_expression] = STATE(49),
    [sym__sub_expression] = STATE(42),
    [sym_variable] = STATE(42),
    [sym__scalar] = STATE(42),
    [sym__number] = STATE(42),
    [sym_integer] = STATE(42),
    [sym_float] = STATE(5),
    [sym_quantity] = STATE(42),
    [sym_call] = STATE(42),
    [sym_binary_operator] = STATE(42),
    [anon_sym_DOT] = ACTIONS(3),
    [sym_NAME] = ACTIONS(5),
    [sym__DIGITS] = ACTIONS(7),
    [sym__SIGN] = ACTIONS(9),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 8,
    ACTIONS(3), 1,
      anon_sym_DOT,
    ACTIONS(5), 1,
      sym_NAME,
    ACTIONS(7), 1,
      sym__DIGITS,
    ACTIONS(9), 1,
      sym__SIGN,
    ACTIONS(11), 1,
      anon_sym_RPAREN,
    STATE(5), 1,
      sym_float,
    STATE(52), 1,
      sym_args,
    STATE(40), 8,
      sym__sub_expression,
      sym_variable,
      sym__scalar,
      sym__number,
      sym_integer,
      sym_quantity,
      sym_call,
      sym_binary_operator,
  [32] = 7,
    ACTIONS(15), 1,
      anon_sym_STAR,
    ACTIONS(17), 1,
      anon_sym_SLASH,
    STATE(13), 1,
      sym_unit,
    STATE(31), 1,
      aux_sym__units_div_part,
    STATE(4), 2,
      aux_sym__units_mult_part,
      sym_unit_term,
    ACTIONS(19), 3,
      aux_sym_unit_token1,
      anon_sym_u00b0,
      anon_sym_PERCENT,
    ACTIONS(13), 5,
      ts_builtin_sym_end,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_PLUS,
      anon_sym_DASH,
  [61] = 7,
    ACTIONS(15), 1,
      anon_sym_STAR,
    ACTIONS(17), 1,
      anon_sym_SLASH,
    STATE(13), 1,
      sym_unit,
    STATE(33), 1,
      aux_sym__units_div_part,
    STATE(9), 2,
      aux_sym__units_mult_part,
      sym_unit_term,
    ACTIONS(19), 3,
      aux_sym_unit_token1,
      anon_sym_u00b0,
      anon_sym_PERCENT,
    ACTIONS(21), 5,
      ts_builtin_sym_end,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_PLUS,
      anon_sym_DASH,
  [90] = 5,
    STATE(3), 1,
      sym_unit_term,
    STATE(13), 1,
      sym_unit,
    STATE(39), 1,
      sym_units,
    ACTIONS(19), 3,
      aux_sym_unit_token1,
      anon_sym_u00b0,
      anon_sym_PERCENT,
    ACTIONS(23), 7,
      ts_builtin_sym_end,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_PLUS,
      anon_sym_DASH,
  [114] = 6,
    ACTIONS(3), 1,
      anon_sym_DOT,
    ACTIONS(5), 1,
      sym_NAME,
    ACTIONS(7), 1,
      sym__DIGITS,
    ACTIONS(9), 1,
      sym__SIGN,
    STATE(5), 1,
      sym_float,
    STATE(36), 8,
      sym__sub_expression,
      sym_variable,
      sym__scalar,
      sym__number,
      sym_integer,
      sym_quantity,
      sym_call,
      sym_binary_operator,
  [140] = 6,
    ACTIONS(3), 1,
      anon_sym_DOT,
    ACTIONS(5), 1,
      sym_NAME,
    ACTIONS(7), 1,
      sym__DIGITS,
    ACTIONS(9), 1,
      sym__SIGN,
    STATE(5), 1,
      sym_float,
    STATE(35), 8,
      sym__sub_expression,
      sym_variable,
      sym__scalar,
      sym__number,
      sym_integer,
      sym_quantity,
      sym_call,
      sym_binary_operator,
  [166] = 6,
    ACTIONS(3), 1,
      anon_sym_DOT,
    ACTIONS(5), 1,
      sym_NAME,
    ACTIONS(7), 1,
      sym__DIGITS,
    ACTIONS(9), 1,
      sym__SIGN,
    STATE(5), 1,
      sym_float,
    STATE(41), 8,
      sym__sub_expression,
      sym_variable,
      sym__scalar,
      sym__number,
      sym_integer,
      sym_quantity,
      sym_call,
      sym_binary_operator,
  [192] = 5,
    ACTIONS(27), 1,
      anon_sym_STAR,
    STATE(13), 1,
      sym_unit,
    STATE(9), 2,
      aux_sym__units_mult_part,
      sym_unit_term,
    ACTIONS(30), 3,
      aux_sym_unit_token1,
      anon_sym_u00b0,
      anon_sym_PERCENT,
    ACTIONS(25), 6,
      ts_builtin_sym_end,
      anon_sym_SLASH,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_PLUS,
      anon_sym_DASH,
  [216] = 5,
    ACTIONS(35), 1,
      anon_sym_DOT,
    ACTIONS(37), 1,
      aux_sym_float_token1,
    ACTIONS(39), 1,
      aux_sym_unit_token1,
    ACTIONS(41), 2,
      anon_sym_u00b0,
      anon_sym_PERCENT,
    ACTIONS(33), 7,
      ts_builtin_sym_end,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_PLUS,
      anon_sym_DASH,
  [239] = 5,
    ACTIONS(45), 1,
      anon_sym_DOT,
    ACTIONS(47), 1,
      aux_sym_float_token1,
    ACTIONS(49), 1,
      aux_sym_unit_token1,
    ACTIONS(51), 2,
      anon_sym_u00b0,
      anon_sym_PERCENT,
    ACTIONS(43), 7,
      ts_builtin_sym_end,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_PLUS,
      anon_sym_DASH,
  [262] = 4,
    ACTIONS(37), 1,
      aux_sym_float_token1,
    ACTIONS(39), 1,
      aux_sym_unit_token1,
    ACTIONS(53), 1,
      sym__DIGITS,
    ACTIONS(41), 9,
      ts_builtin_sym_end,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_u00b0,
      anon_sym_PERCENT,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_PLUS,
      anon_sym_DASH,
  [283] = 3,
    ACTIONS(57), 1,
      anon_sym_STAR,
    ACTIONS(59), 2,
      anon_sym_CARET,
      anon_sym_STAR_STAR,
    ACTIONS(55), 9,
      ts_builtin_sym_end,
      anon_sym_SLASH,
      aux_sym_unit_token1,
      anon_sym_u00b0,
      anon_sym_PERCENT,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_PLUS,
      anon_sym_DASH,
  [302] = 2,
    ACTIONS(63), 1,
      anon_sym_STAR,
    ACTIONS(61), 11,
      ts_builtin_sym_end,
      anon_sym_SLASH,
      anon_sym_CARET,
      anon_sym_STAR_STAR,
      aux_sym_unit_token1,
      anon_sym_u00b0,
      anon_sym_PERCENT,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_PLUS,
      anon_sym_DASH,
  [319] = 4,
    ACTIONS(67), 1,
      aux_sym_float_token1,
    ACTIONS(69), 1,
      sym__DIGITS,
    ACTIONS(71), 1,
      aux_sym_unit_token1,
    ACTIONS(65), 9,
      ts_builtin_sym_end,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_u00b0,
      anon_sym_PERCENT,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_PLUS,
      anon_sym_DASH,
  [340] = 5,
    ACTIONS(75), 1,
      anon_sym_DOT,
    ACTIONS(77), 1,
      anon_sym_LPAREN,
    STATE(25), 1,
      aux_sym_variable_repeat1,
    STATE(51), 1,
      sym__DOT,
    ACTIONS(73), 7,
      ts_builtin_sym_end,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_PLUS,
      anon_sym_DASH,
  [362] = 3,
    ACTIONS(37), 1,
      aux_sym_float_token1,
    ACTIONS(39), 1,
      aux_sym_unit_token1,
    ACTIONS(41), 9,
      ts_builtin_sym_end,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_u00b0,
      anon_sym_PERCENT,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_PLUS,
      anon_sym_DASH,
  [380] = 3,
    ACTIONS(67), 1,
      aux_sym_float_token1,
    ACTIONS(71), 1,
      aux_sym_unit_token1,
    ACTIONS(65), 9,
      ts_builtin_sym_end,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_u00b0,
      anon_sym_PERCENT,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_PLUS,
      anon_sym_DASH,
  [398] = 3,
    ACTIONS(81), 1,
      aux_sym_float_token1,
    ACTIONS(83), 1,
      aux_sym_unit_token1,
    ACTIONS(79), 9,
      ts_builtin_sym_end,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_u00b0,
      anon_sym_PERCENT,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_PLUS,
      anon_sym_DASH,
  [416] = 4,
    ACTIONS(87), 1,
      anon_sym_DOT,
    STATE(20), 1,
      aux_sym_variable_repeat1,
    STATE(51), 1,
      sym__DOT,
    ACTIONS(85), 7,
      ts_builtin_sym_end,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_PLUS,
      anon_sym_DASH,
  [435] = 1,
    ACTIONS(90), 10,
      ts_builtin_sym_end,
      anon_sym_STAR,
      anon_sym_SLASH,
      aux_sym_unit_token1,
      anon_sym_u00b0,
      anon_sym_PERCENT,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_PLUS,
      anon_sym_DASH,
  [448] = 1,
    ACTIONS(65), 10,
      ts_builtin_sym_end,
      anon_sym_STAR,
      anon_sym_SLASH,
      aux_sym_unit_token1,
      anon_sym_u00b0,
      anon_sym_PERCENT,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_PLUS,
      anon_sym_DASH,
  [461] = 1,
    ACTIONS(79), 10,
      ts_builtin_sym_end,
      anon_sym_STAR,
      anon_sym_SLASH,
      aux_sym_unit_token1,
      anon_sym_u00b0,
      anon_sym_PERCENT,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_PLUS,
      anon_sym_DASH,
  [474] = 1,
    ACTIONS(25), 10,
      ts_builtin_sym_end,
      anon_sym_STAR,
      anon_sym_SLASH,
      aux_sym_unit_token1,
      anon_sym_u00b0,
      anon_sym_PERCENT,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_PLUS,
      anon_sym_DASH,
  [487] = 4,
    ACTIONS(75), 1,
      anon_sym_DOT,
    STATE(20), 1,
      aux_sym_variable_repeat1,
    STATE(51), 1,
      sym__DOT,
    ACTIONS(92), 7,
      ts_builtin_sym_end,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_PLUS,
      anon_sym_DASH,
  [506] = 1,
    ACTIONS(43), 10,
      ts_builtin_sym_end,
      anon_sym_STAR,
      anon_sym_SLASH,
      aux_sym_unit_token1,
      anon_sym_u00b0,
      anon_sym_PERCENT,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_PLUS,
      anon_sym_DASH,
  [519] = 1,
    ACTIONS(94), 10,
      ts_builtin_sym_end,
      anon_sym_STAR,
      anon_sym_SLASH,
      aux_sym_unit_token1,
      anon_sym_u00b0,
      anon_sym_PERCENT,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_PLUS,
      anon_sym_DASH,
  [532] = 1,
    ACTIONS(96), 10,
      ts_builtin_sym_end,
      anon_sym_STAR,
      anon_sym_SLASH,
      aux_sym_unit_token1,
      anon_sym_u00b0,
      anon_sym_PERCENT,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_PLUS,
      anon_sym_DASH,
  [545] = 1,
    ACTIONS(33), 10,
      ts_builtin_sym_end,
      anon_sym_STAR,
      anon_sym_SLASH,
      aux_sym_unit_token1,
      anon_sym_u00b0,
      anon_sym_PERCENT,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_PLUS,
      anon_sym_DASH,
  [558] = 3,
    ACTIONS(100), 1,
      anon_sym_SLASH,
    STATE(30), 1,
      aux_sym__units_div_part,
    ACTIONS(98), 6,
      ts_builtin_sym_end,
      anon_sym_STAR,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_PLUS,
      anon_sym_DASH,
  [573] = 3,
    ACTIONS(17), 1,
      anon_sym_SLASH,
    STATE(30), 1,
      aux_sym__units_div_part,
    ACTIONS(103), 6,
      ts_builtin_sym_end,
      anon_sym_STAR,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_PLUS,
      anon_sym_DASH,
  [588] = 1,
    ACTIONS(85), 8,
      ts_builtin_sym_end,
      anon_sym_DOT,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_PLUS,
      anon_sym_DASH,
  [599] = 3,
    ACTIONS(17), 1,
      anon_sym_SLASH,
    STATE(30), 1,
      aux_sym__units_div_part,
    ACTIONS(105), 6,
      ts_builtin_sym_end,
      anon_sym_STAR,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_PLUS,
      anon_sym_DASH,
  [614] = 1,
    ACTIONS(107), 7,
      ts_builtin_sym_end,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_PLUS,
      anon_sym_DASH,
  [624] = 2,
    ACTIONS(111), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(109), 5,
      ts_builtin_sym_end,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_PLUS,
      anon_sym_DASH,
  [636] = 1,
    ACTIONS(109), 7,
      ts_builtin_sym_end,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_PLUS,
      anon_sym_DASH,
  [646] = 1,
    ACTIONS(113), 7,
      ts_builtin_sym_end,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_PLUS,
      anon_sym_DASH,
  [656] = 1,
    ACTIONS(98), 7,
      ts_builtin_sym_end,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_PLUS,
      anon_sym_DASH,
  [666] = 1,
    ACTIONS(115), 7,
      ts_builtin_sym_end,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_PLUS,
      anon_sym_DASH,
  [676] = 5,
    ACTIONS(117), 1,
      anon_sym_RPAREN,
    ACTIONS(119), 1,
      anon_sym_COMMA,
    STATE(46), 1,
      aux_sym_args_repeat1,
    ACTIONS(111), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(121), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
  [694] = 3,
    ACTIONS(111), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(121), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(123), 2,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [707] = 3,
    ACTIONS(125), 1,
      ts_builtin_sym_end,
    ACTIONS(111), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(121), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
  [719] = 3,
    STATE(13), 1,
      sym_unit,
    STATE(24), 1,
      sym_unit_term,
    ACTIONS(19), 3,
      aux_sym_unit_token1,
      anon_sym_u00b0,
      anon_sym_PERCENT,
  [731] = 3,
    STATE(13), 1,
      sym_unit,
    STATE(38), 1,
      sym_unit_term,
    ACTIONS(19), 3,
      aux_sym_unit_token1,
      anon_sym_u00b0,
      anon_sym_PERCENT,
  [743] = 3,
    ACTIONS(127), 1,
      sym__DIGITS,
    ACTIONS(129), 1,
      sym__SIGN,
    STATE(27), 1,
      sym_integer,
  [753] = 3,
    ACTIONS(119), 1,
      anon_sym_COMMA,
    ACTIONS(131), 1,
      anon_sym_RPAREN,
    STATE(47), 1,
      aux_sym_args_repeat1,
  [763] = 3,
    ACTIONS(123), 1,
      anon_sym_RPAREN,
    ACTIONS(133), 1,
      anon_sym_COMMA,
    STATE(47), 1,
      aux_sym_args_repeat1,
  [773] = 2,
    ACTIONS(136), 1,
      anon_sym_DOT,
    ACTIONS(138), 1,
      sym__DIGITS,
  [780] = 1,
    ACTIONS(140), 1,
      ts_builtin_sym_end,
  [784] = 1,
    ACTIONS(142), 1,
      sym__DIGITS,
  [788] = 1,
    ACTIONS(144), 1,
      sym_NAME,
  [792] = 1,
    ACTIONS(146), 1,
      anon_sym_RPAREN,
  [796] = 1,
    ACTIONS(148), 1,
      sym__DIGITS,
  [800] = 1,
    ACTIONS(150), 1,
      sym__DIGITS,
  [804] = 1,
    ACTIONS(53), 1,
      sym__DIGITS,
  [808] = 1,
    ACTIONS(152), 1,
      sym__DIGITS,
  [812] = 1,
    ACTIONS(154), 1,
      sym__DIGITS,
  [816] = 1,
    ACTIONS(156), 1,
      sym__DIGITS,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 32,
  [SMALL_STATE(4)] = 61,
  [SMALL_STATE(5)] = 90,
  [SMALL_STATE(6)] = 114,
  [SMALL_STATE(7)] = 140,
  [SMALL_STATE(8)] = 166,
  [SMALL_STATE(9)] = 192,
  [SMALL_STATE(10)] = 216,
  [SMALL_STATE(11)] = 239,
  [SMALL_STATE(12)] = 262,
  [SMALL_STATE(13)] = 283,
  [SMALL_STATE(14)] = 302,
  [SMALL_STATE(15)] = 319,
  [SMALL_STATE(16)] = 340,
  [SMALL_STATE(17)] = 362,
  [SMALL_STATE(18)] = 380,
  [SMALL_STATE(19)] = 398,
  [SMALL_STATE(20)] = 416,
  [SMALL_STATE(21)] = 435,
  [SMALL_STATE(22)] = 448,
  [SMALL_STATE(23)] = 461,
  [SMALL_STATE(24)] = 474,
  [SMALL_STATE(25)] = 487,
  [SMALL_STATE(26)] = 506,
  [SMALL_STATE(27)] = 519,
  [SMALL_STATE(28)] = 532,
  [SMALL_STATE(29)] = 545,
  [SMALL_STATE(30)] = 558,
  [SMALL_STATE(31)] = 573,
  [SMALL_STATE(32)] = 588,
  [SMALL_STATE(33)] = 599,
  [SMALL_STATE(34)] = 614,
  [SMALL_STATE(35)] = 624,
  [SMALL_STATE(36)] = 636,
  [SMALL_STATE(37)] = 646,
  [SMALL_STATE(38)] = 656,
  [SMALL_STATE(39)] = 666,
  [SMALL_STATE(40)] = 676,
  [SMALL_STATE(41)] = 694,
  [SMALL_STATE(42)] = 707,
  [SMALL_STATE(43)] = 719,
  [SMALL_STATE(44)] = 731,
  [SMALL_STATE(45)] = 743,
  [SMALL_STATE(46)] = 753,
  [SMALL_STATE(47)] = 763,
  [SMALL_STATE(48)] = 773,
  [SMALL_STATE(49)] = 780,
  [SMALL_STATE(50)] = 784,
  [SMALL_STATE(51)] = 788,
  [SMALL_STATE(52)] = 792,
  [SMALL_STATE(53)] = 796,
  [SMALL_STATE(54)] = 800,
  [SMALL_STATE(55)] = 804,
  [SMALL_STATE(56)] = 808,
  [SMALL_STATE(57)] = 812,
  [SMALL_STATE(58)] = 816,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [13] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_units, 1, 0, 2),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [21] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_units, 2, 0, 6),
  [23] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__number, 1, 0, 0),
  [25] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__units_mult_part, 2, 0, 0),
  [27] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__units_mult_part, 2, 0, 0), SHIFT_REPEAT(43),
  [30] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__units_mult_part, 2, 0, 0), SHIFT_REPEAT(14),
  [33] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_integer, 2, 0, 0),
  [35] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [37] = {.entry = {.count = 1, .reusable = false}}, SHIFT(57),
  [39] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_float, 2, 0, 0),
  [41] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_float, 2, 0, 0),
  [43] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_integer, 1, 0, 0),
  [45] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [47] = {.entry = {.count = 1, .reusable = false}}, SHIFT(54),
  [49] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_float, 1, 0, 0),
  [51] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_float, 1, 0, 0),
  [53] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [55] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_unit_term, 1, 0, 3),
  [57] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_unit_term, 1, 0, 3),
  [59] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [61] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_unit, 1, 0, 0),
  [63] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_unit, 1, 0, 0),
  [65] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_float, 3, 0, 0),
  [67] = {.entry = {.count = 1, .reusable = false}}, SHIFT(50),
  [69] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [71] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_float, 3, 0, 0),
  [73] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_variable, 1, 0, 0),
  [75] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [77] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [79] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_float, 4, 0, 0),
  [81] = {.entry = {.count = 1, .reusable = false}}, SHIFT(56),
  [83] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_float, 4, 0, 0),
  [85] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_variable_repeat1, 2, 0, 0),
  [87] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_variable_repeat1, 2, 0, 0), SHIFT_REPEAT(51),
  [90] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_float, 6, 0, 0),
  [92] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_variable, 2, 0, 0),
  [94] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_unit_term, 3, 0, 10),
  [96] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_float, 5, 0, 0),
  [98] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__units_div_part, 2, 0, 0),
  [100] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__units_div_part, 2, 0, 0), SHIFT_REPEAT(44),
  [103] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_units, 2, 0, 7),
  [105] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_units, 3, 0, 9),
  [107] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_call, 4, 0, 8),
  [109] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_binary_operator, 3, 0, 5),
  [111] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [113] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_call, 3, 0, 4),
  [115] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_quantity, 2, 0, 1),
  [117] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_args, 1, 0, 0),
  [119] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [121] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [123] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_args_repeat1, 2, 0, 0),
  [125] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression, 1, 0, 0),
  [127] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [129] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [131] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_args, 2, 0, 0),
  [133] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_args_repeat1, 2, 0, 0), SHIFT_REPEAT(8),
  [136] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [138] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [140] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [142] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [144] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [146] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [148] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [150] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [152] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [154] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [156] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_caqtus(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
