#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 86
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 33
#define ALIAS_COUNT 0
#define TOKEN_COUNT 15
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 9
#define MAX_ALIAS_SEQUENCE_LENGTH 6
#define PRODUCTION_ID_COUNT 11

enum ts_symbol_identifiers {
  anon_sym_DOT = 1,
  sym_NAME = 2,
  aux_sym_float_token1 = 3,
  sym__DIGITS = 4,
  sym__SIGN = 5,
  anon_sym_STAR = 6,
  anon_sym_SLASH = 7,
  anon_sym_CARET = 8,
  anon_sym_STAR_STAR = 9,
  sym__SINGLE_UNIT = 10,
  anon_sym_LPAREN = 11,
  anon_sym_RPAREN = 12,
  anon_sym_COMMA = 13,
  anon_sym_EQ = 14,
  sym_expression = 15,
  sym_variable = 16,
  sym__scalar = 17,
  sym__number = 18,
  sym_integer = 19,
  sym_float = 20,
  sym_quantity = 21,
  sym_unit = 22,
  sym_unit_term = 23,
  sym_call = 24,
  sym_args = 25,
  sym_kwargs = 26,
  sym_kwarg = 27,
  aux_sym_variable_repeat1 = 28,
  aux_sym_unit_repeat1 = 29,
  aux_sym_unit_repeat2 = 30,
  aux_sym_args_repeat1 = 31,
  aux_sym_kwargs_repeat1 = 32,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_DOT] = ".",
  [sym_NAME] = "NAME",
  [aux_sym_float_token1] = "float_token1",
  [sym__DIGITS] = "_DIGITS",
  [sym__SIGN] = "_SIGN",
  [anon_sym_STAR] = "*",
  [anon_sym_SLASH] = "/",
  [anon_sym_CARET] = "^",
  [anon_sym_STAR_STAR] = "**",
  [sym__SINGLE_UNIT] = "_SINGLE_UNIT",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_COMMA] = ",",
  [anon_sym_EQ] = "=",
  [sym_expression] = "expression",
  [sym_variable] = "variable",
  [sym__scalar] = "_scalar",
  [sym__number] = "_number",
  [sym_integer] = "integer",
  [sym_float] = "float",
  [sym_quantity] = "quantity",
  [sym_unit] = "unit",
  [sym_unit_term] = "unit_term",
  [sym_call] = "call",
  [sym_args] = "args",
  [sym_kwargs] = "kwargs",
  [sym_kwarg] = "kwarg",
  [aux_sym_variable_repeat1] = "variable_repeat1",
  [aux_sym_unit_repeat1] = "unit_repeat1",
  [aux_sym_unit_repeat2] = "unit_repeat2",
  [aux_sym_args_repeat1] = "args_repeat1",
  [aux_sym_kwargs_repeat1] = "kwargs_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_DOT] = anon_sym_DOT,
  [sym_NAME] = sym_NAME,
  [aux_sym_float_token1] = aux_sym_float_token1,
  [sym__DIGITS] = sym__DIGITS,
  [sym__SIGN] = sym__SIGN,
  [anon_sym_STAR] = anon_sym_STAR,
  [anon_sym_SLASH] = anon_sym_SLASH,
  [anon_sym_CARET] = anon_sym_CARET,
  [anon_sym_STAR_STAR] = anon_sym_STAR_STAR,
  [sym__SINGLE_UNIT] = sym__SINGLE_UNIT,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_EQ] = anon_sym_EQ,
  [sym_expression] = sym_expression,
  [sym_variable] = sym_variable,
  [sym__scalar] = sym__scalar,
  [sym__number] = sym__number,
  [sym_integer] = sym_integer,
  [sym_float] = sym_float,
  [sym_quantity] = sym_quantity,
  [sym_unit] = sym_unit,
  [sym_unit_term] = sym_unit_term,
  [sym_call] = sym_call,
  [sym_args] = sym_args,
  [sym_kwargs] = sym_kwargs,
  [sym_kwarg] = sym_kwarg,
  [aux_sym_variable_repeat1] = aux_sym_variable_repeat1,
  [aux_sym_unit_repeat1] = aux_sym_unit_repeat1,
  [aux_sym_unit_repeat2] = aux_sym_unit_repeat2,
  [aux_sym_args_repeat1] = aux_sym_args_repeat1,
  [aux_sym_kwargs_repeat1] = aux_sym_kwargs_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = false,
  },
  [sym_NAME] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_float_token1] = {
    .visible = false,
    .named = false,
  },
  [sym__DIGITS] = {
    .visible = false,
    .named = true,
  },
  [sym__SIGN] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_STAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_CARET] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_STAR_STAR] = {
    .visible = true,
    .named = false,
  },
  [sym__SINGLE_UNIT] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [sym_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_variable] = {
    .visible = true,
    .named = true,
  },
  [sym__scalar] = {
    .visible = false,
    .named = true,
  },
  [sym__number] = {
    .visible = false,
    .named = true,
  },
  [sym_integer] = {
    .visible = true,
    .named = true,
  },
  [sym_float] = {
    .visible = true,
    .named = true,
  },
  [sym_quantity] = {
    .visible = true,
    .named = true,
  },
  [sym_unit] = {
    .visible = true,
    .named = true,
  },
  [sym_unit_term] = {
    .visible = true,
    .named = true,
  },
  [sym_call] = {
    .visible = true,
    .named = true,
  },
  [sym_args] = {
    .visible = true,
    .named = true,
  },
  [sym_kwargs] = {
    .visible = true,
    .named = true,
  },
  [sym_kwarg] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_variable_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_unit_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_unit_repeat2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_args_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_kwargs_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_args = 1,
  field_base = 2,
  field_divisive = 3,
  field_exponent = 4,
  field_function = 5,
  field_kwargs = 6,
  field_magnitude = 7,
  field_multiplicative = 8,
  field_unit = 9,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_args] = "args",
  [field_base] = "base",
  [field_divisive] = "divisive",
  [field_exponent] = "exponent",
  [field_function] = "function",
  [field_kwargs] = "kwargs",
  [field_magnitude] = "magnitude",
  [field_multiplicative] = "multiplicative",
  [field_unit] = "unit",
};

static const TSFieldMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 2},
  [3] = {.index = 3, .length = 1},
  [4] = {.index = 4, .length = 2},
  [5] = {.index = 6, .length = 2},
  [6] = {.index = 8, .length = 2},
  [7] = {.index = 10, .length = 2},
  [8] = {.index = 12, .length = 3},
  [9] = {.index = 15, .length = 3},
  [10] = {.index = 18, .length = 3},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_base, 0},
  [1] =
    {field_magnitude, 0},
    {field_unit, 1},
  [3] =
    {field_function, 0},
  [4] =
    {field_base, 0},
    {field_multiplicative, 1},
  [6] =
    {field_base, 0},
    {field_divisive, 1},
  [8] =
    {field_args, 2},
    {field_function, 0},
  [10] =
    {field_function, 0},
    {field_kwargs, 2},
  [12] =
    {field_base, 0},
    {field_exponent, 1},
    {field_exponent, 2},
  [15] =
    {field_base, 0},
    {field_divisive, 2},
    {field_multiplicative, 1},
  [18] =
    {field_args, 2},
    {field_function, 0},
    {field_kwargs, 3},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 11,
  [25] = 16,
  [26] = 12,
  [27] = 13,
  [28] = 15,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 33,
  [35] = 31,
  [36] = 36,
  [37] = 36,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 38,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 46,
  [52] = 52,
  [53] = 43,
  [54] = 54,
  [55] = 52,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 65,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 73,
  [74] = 74,
  [75] = 75,
  [76] = 76,
  [77] = 77,
  [78] = 78,
  [79] = 78,
  [80] = 80,
  [81] = 69,
  [82] = 75,
  [83] = 77,
  [84] = 70,
  [85] = 71,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(4);
      ADVANCE_MAP(
        '(', 20,
        ')', 21,
        '*', 14,
        ',', 22,
        '.', 5,
        '/', 15,
        '=', 23,
        '^', 16,
        '%', 18,
        0xb0, 18,
        '+', 13,
        '-', 13,
        'E', 6,
        'e', 6,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(11);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(7);
      END_STATE();
    case 1:
      if (lookahead == ')') ADVANCE(21);
      if (lookahead == ',') ADVANCE(22);
      if (lookahead == '%' ||
          lookahead == 0xb0) ADVANCE(18);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(1);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(7);
      END_STATE();
    case 2:
      if (eof) ADVANCE(4);
      if (lookahead == ')') ADVANCE(21);
      if (lookahead == ',') ADVANCE(22);
      if (lookahead == '.') ADVANCE(5);
      if (lookahead == '%' ||
          lookahead == 0xb0) ADVANCE(18);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(10);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(2);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(11);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(19);
      END_STATE();
    case 3:
      if (eof) ADVANCE(4);
      if (lookahead == ')') ADVANCE(21);
      if (lookahead == ',') ADVANCE(22);
      if (lookahead == '%' ||
          lookahead == 0xb0) ADVANCE(18);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(3);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(19);
      END_STATE();
    case 4:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 5:
      ACCEPT_TOKEN(anon_sym_DOT);
      END_STATE();
    case 6:
      ACCEPT_TOKEN(sym_NAME);
      if (lookahead == '+' ||
          lookahead == '-') ADVANCE(9);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_') ADVANCE(8);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(7);
      END_STATE();
    case 7:
      ACCEPT_TOKEN(sym_NAME);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_') ADVANCE(8);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(7);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(sym_NAME);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(8);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(aux_sym_float_token1);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(aux_sym_float_token1);
      if (lookahead == '+' ||
          lookahead == '-') ADVANCE(9);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(19);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(sym__DIGITS);
      if (lookahead == '_') ADVANCE(12);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(11);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(sym__DIGITS);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(11);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(sym__SIGN);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(anon_sym_STAR);
      if (lookahead == '*') ADVANCE(17);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(anon_sym_SLASH);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(anon_sym_CARET);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_STAR_STAR);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(sym__SINGLE_UNIT);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(sym__SINGLE_UNIT);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(19);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 2},
  [12] = {.lex_state = 2},
  [13] = {.lex_state = 2},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 2},
  [16] = {.lex_state = 3},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 1},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 2},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 2},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 2},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 1},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 3},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 3},
  [47] = {.lex_state = 3},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 0},
  [51] = {.lex_state = 1},
  [52] = {.lex_state = 3},
  [53] = {.lex_state = 1},
  [54] = {.lex_state = 0},
  [55] = {.lex_state = 1},
  [56] = {.lex_state = 0},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 0},
  [59] = {.lex_state = 0},
  [60] = {.lex_state = 0},
  [61] = {.lex_state = 3},
  [62] = {.lex_state = 0},
  [63] = {.lex_state = 3},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 0},
  [66] = {.lex_state = 0},
  [67] = {.lex_state = 0},
  [68] = {.lex_state = 0},
  [69] = {.lex_state = 0},
  [70] = {.lex_state = 0},
  [71] = {.lex_state = 0},
  [72] = {.lex_state = 0},
  [73] = {.lex_state = 0},
  [74] = {.lex_state = 0},
  [75] = {.lex_state = 0},
  [76] = {.lex_state = 0},
  [77] = {.lex_state = 0},
  [78] = {.lex_state = 0},
  [79] = {.lex_state = 0},
  [80] = {.lex_state = 0},
  [81] = {.lex_state = 0},
  [82] = {.lex_state = 0},
  [83] = {.lex_state = 0},
  [84] = {.lex_state = 0},
  [85] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_DOT] = ACTIONS(1),
    [sym_NAME] = ACTIONS(1),
    [aux_sym_float_token1] = ACTIONS(1),
    [sym__DIGITS] = ACTIONS(1),
    [sym__SIGN] = ACTIONS(1),
    [anon_sym_STAR] = ACTIONS(1),
    [anon_sym_SLASH] = ACTIONS(1),
    [anon_sym_CARET] = ACTIONS(1),
    [anon_sym_STAR_STAR] = ACTIONS(1),
    [sym__SINGLE_UNIT] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
  },
  [1] = {
    [sym_expression] = STATE(72),
    [sym_variable] = STATE(44),
    [sym__scalar] = STATE(44),
    [sym__number] = STATE(44),
    [sym_integer] = STATE(44),
    [sym_float] = STATE(16),
    [sym_quantity] = STATE(44),
    [sym_call] = STATE(44),
    [anon_sym_DOT] = ACTIONS(3),
    [sym_NAME] = ACTIONS(5),
    [sym__DIGITS] = ACTIONS(7),
    [sym__SIGN] = ACTIONS(9),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 11,
    ACTIONS(11), 1,
      anon_sym_DOT,
    ACTIONS(13), 1,
      sym_NAME,
    ACTIONS(15), 1,
      sym__DIGITS,
    ACTIONS(17), 1,
      sym__SIGN,
    ACTIONS(19), 1,
      anon_sym_RPAREN,
    STATE(25), 1,
      sym_float,
    STATE(50), 1,
      sym_expression,
    STATE(54), 1,
      sym_args,
    STATE(59), 1,
      sym_kwarg,
    STATE(73), 1,
      sym_kwargs,
    STATE(44), 6,
      sym_variable,
      sym__scalar,
      sym__number,
      sym_integer,
      sym_quantity,
      sym_call,
  [39] = 7,
    ACTIONS(3), 1,
      anon_sym_DOT,
    ACTIONS(5), 1,
      sym_NAME,
    ACTIONS(7), 1,
      sym__DIGITS,
    ACTIONS(9), 1,
      sym__SIGN,
    STATE(16), 1,
      sym_float,
    STATE(67), 1,
      sym_expression,
    STATE(44), 6,
      sym_variable,
      sym__scalar,
      sym__number,
      sym_integer,
      sym_quantity,
      sym_call,
  [66] = 7,
    ACTIONS(5), 1,
      sym_NAME,
    ACTIONS(11), 1,
      anon_sym_DOT,
    ACTIONS(15), 1,
      sym__DIGITS,
    ACTIONS(17), 1,
      sym__SIGN,
    STATE(25), 1,
      sym_float,
    STATE(56), 1,
      sym_expression,
    STATE(44), 6,
      sym_variable,
      sym__scalar,
      sym__number,
      sym_integer,
      sym_quantity,
      sym_call,
  [93] = 5,
    ACTIONS(23), 1,
      anon_sym_STAR,
    ACTIONS(25), 1,
      anon_sym_SLASH,
    STATE(10), 1,
      aux_sym_unit_repeat1,
    STATE(21), 1,
      aux_sym_unit_repeat2,
    ACTIONS(21), 4,
      ts_builtin_sym_end,
      sym_NAME,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [112] = 5,
    ACTIONS(23), 1,
      anon_sym_STAR,
    ACTIONS(25), 1,
      anon_sym_SLASH,
    STATE(5), 1,
      aux_sym_unit_repeat1,
    STATE(17), 1,
      aux_sym_unit_repeat2,
    ACTIONS(27), 4,
      ts_builtin_sym_end,
      sym_NAME,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [131] = 3,
    ACTIONS(31), 1,
      anon_sym_STAR,
    ACTIONS(33), 2,
      anon_sym_CARET,
      anon_sym_STAR_STAR,
    ACTIONS(29), 5,
      ts_builtin_sym_end,
      sym_NAME,
      anon_sym_SLASH,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [146] = 5,
    ACTIONS(35), 1,
      anon_sym_DOT,
    ACTIONS(39), 1,
      anon_sym_LPAREN,
    ACTIONS(41), 1,
      anon_sym_EQ,
    STATE(29), 1,
      aux_sym_variable_repeat1,
    ACTIONS(37), 3,
      sym_NAME,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [164] = 4,
    ACTIONS(35), 1,
      anon_sym_DOT,
    ACTIONS(39), 1,
      anon_sym_LPAREN,
    STATE(29), 1,
      aux_sym_variable_repeat1,
    ACTIONS(37), 4,
      ts_builtin_sym_end,
      sym_NAME,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [180] = 3,
    ACTIONS(45), 1,
      anon_sym_STAR,
    STATE(10), 1,
      aux_sym_unit_repeat1,
    ACTIONS(43), 5,
      ts_builtin_sym_end,
      sym_NAME,
      anon_sym_SLASH,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [194] = 4,
    ACTIONS(50), 1,
      anon_sym_DOT,
    ACTIONS(52), 1,
      aux_sym_float_token1,
    ACTIONS(54), 1,
      sym__SINGLE_UNIT,
    ACTIONS(48), 3,
      ts_builtin_sym_end,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [209] = 4,
    ACTIONS(58), 1,
      aux_sym_float_token1,
    ACTIONS(60), 1,
      sym__DIGITS,
    ACTIONS(62), 1,
      sym__SINGLE_UNIT,
    ACTIONS(56), 3,
      ts_builtin_sym_end,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [224] = 4,
    ACTIONS(58), 1,
      aux_sym_float_token1,
    ACTIONS(62), 1,
      sym__SINGLE_UNIT,
    ACTIONS(66), 1,
      anon_sym_DOT,
    ACTIONS(64), 3,
      ts_builtin_sym_end,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [239] = 3,
    ACTIONS(70), 1,
      anon_sym_DOT,
    STATE(14), 1,
      aux_sym_variable_repeat1,
    ACTIONS(68), 4,
      ts_builtin_sym_end,
      sym_NAME,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [252] = 4,
    ACTIONS(75), 1,
      aux_sym_float_token1,
    ACTIONS(77), 1,
      sym__DIGITS,
    ACTIONS(79), 1,
      sym__SINGLE_UNIT,
    ACTIONS(73), 3,
      ts_builtin_sym_end,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [267] = 4,
    ACTIONS(83), 1,
      sym__SINGLE_UNIT,
    STATE(6), 1,
      sym_unit_term,
    STATE(40), 1,
      sym_unit,
    ACTIONS(81), 3,
      ts_builtin_sym_end,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [282] = 3,
    ACTIONS(25), 1,
      anon_sym_SLASH,
    STATE(22), 1,
      aux_sym_unit_repeat2,
    ACTIONS(85), 4,
      ts_builtin_sym_end,
      sym_NAME,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [295] = 1,
    ACTIONS(48), 6,
      ts_builtin_sym_end,
      sym_NAME,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [304] = 1,
    ACTIONS(87), 6,
      ts_builtin_sym_end,
      sym_NAME,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [313] = 1,
    ACTIONS(43), 6,
      ts_builtin_sym_end,
      sym_NAME,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [322] = 3,
    ACTIONS(25), 1,
      anon_sym_SLASH,
    STATE(22), 1,
      aux_sym_unit_repeat2,
    ACTIONS(89), 4,
      ts_builtin_sym_end,
      sym_NAME,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [335] = 3,
    ACTIONS(93), 1,
      anon_sym_SLASH,
    STATE(22), 1,
      aux_sym_unit_repeat2,
    ACTIONS(91), 4,
      ts_builtin_sym_end,
      sym_NAME,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [348] = 1,
    ACTIONS(64), 6,
      ts_builtin_sym_end,
      sym_NAME,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [357] = 5,
    ACTIONS(54), 1,
      sym__SINGLE_UNIT,
    ACTIONS(96), 1,
      anon_sym_DOT,
    ACTIONS(98), 1,
      sym_NAME,
    ACTIONS(100), 1,
      aux_sym_float_token1,
    ACTIONS(48), 2,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [374] = 4,
    ACTIONS(102), 1,
      sym__SINGLE_UNIT,
    STATE(6), 1,
      sym_unit_term,
    STATE(40), 1,
      sym_unit,
    ACTIONS(81), 3,
      sym_NAME,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [389] = 4,
    ACTIONS(104), 1,
      aux_sym_float_token1,
    ACTIONS(106), 1,
      sym__DIGITS,
    ACTIONS(56), 2,
      anon_sym_RPAREN,
      anon_sym_COMMA,
    ACTIONS(62), 2,
      sym_NAME,
      sym__SINGLE_UNIT,
  [404] = 5,
    ACTIONS(62), 1,
      sym__SINGLE_UNIT,
    ACTIONS(104), 1,
      aux_sym_float_token1,
    ACTIONS(108), 1,
      anon_sym_DOT,
    ACTIONS(110), 1,
      sym_NAME,
    ACTIONS(64), 2,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [421] = 4,
    ACTIONS(112), 1,
      aux_sym_float_token1,
    ACTIONS(114), 1,
      sym__DIGITS,
    ACTIONS(73), 2,
      anon_sym_RPAREN,
      anon_sym_COMMA,
    ACTIONS(79), 2,
      sym_NAME,
      sym__SINGLE_UNIT,
  [436] = 3,
    ACTIONS(35), 1,
      anon_sym_DOT,
    STATE(14), 1,
      aux_sym_variable_repeat1,
    ACTIONS(116), 4,
      ts_builtin_sym_end,
      sym_NAME,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [449] = 1,
    ACTIONS(68), 5,
      ts_builtin_sym_end,
      anon_sym_DOT,
      sym_NAME,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [457] = 3,
    ACTIONS(58), 1,
      aux_sym_float_token1,
    ACTIONS(62), 1,
      sym__SINGLE_UNIT,
    ACTIONS(56), 3,
      ts_builtin_sym_end,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [469] = 1,
    ACTIONS(91), 5,
      ts_builtin_sym_end,
      sym_NAME,
      anon_sym_SLASH,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [477] = 3,
    ACTIONS(120), 1,
      aux_sym_float_token1,
    ACTIONS(122), 1,
      sym__SINGLE_UNIT,
    ACTIONS(118), 3,
      ts_builtin_sym_end,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [489] = 3,
    ACTIONS(124), 1,
      aux_sym_float_token1,
    ACTIONS(118), 2,
      anon_sym_RPAREN,
      anon_sym_COMMA,
    ACTIONS(122), 2,
      sym_NAME,
      sym__SINGLE_UNIT,
  [501] = 3,
    ACTIONS(104), 1,
      aux_sym_float_token1,
    ACTIONS(56), 2,
      anon_sym_RPAREN,
      anon_sym_COMMA,
    ACTIONS(62), 2,
      sym_NAME,
      sym__SINGLE_UNIT,
  [513] = 3,
    ACTIONS(75), 1,
      aux_sym_float_token1,
    ACTIONS(79), 1,
      sym__SINGLE_UNIT,
    ACTIONS(73), 3,
      ts_builtin_sym_end,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [525] = 3,
    ACTIONS(112), 1,
      aux_sym_float_token1,
    ACTIONS(73), 2,
      anon_sym_RPAREN,
      anon_sym_COMMA,
    ACTIONS(79), 2,
      sym_NAME,
      sym__SINGLE_UNIT,
  [537] = 2,
    ACTIONS(128), 1,
      sym__SINGLE_UNIT,
    ACTIONS(126), 3,
      sym_NAME,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [546] = 1,
    ACTIONS(130), 4,
      ts_builtin_sym_end,
      sym_NAME,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [553] = 1,
    ACTIONS(132), 4,
      ts_builtin_sym_end,
      sym_NAME,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [560] = 3,
    ACTIONS(136), 1,
      anon_sym_COMMA,
    STATE(48), 1,
      aux_sym_args_repeat1,
    ACTIONS(134), 2,
      sym_NAME,
      anon_sym_RPAREN,
  [571] = 1,
    ACTIONS(138), 4,
      ts_builtin_sym_end,
      sym_NAME,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [578] = 1,
    ACTIONS(118), 4,
      ts_builtin_sym_end,
      sym__SINGLE_UNIT,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [585] = 1,
    ACTIONS(140), 4,
      ts_builtin_sym_end,
      sym_NAME,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [592] = 1,
    ACTIONS(142), 4,
      ts_builtin_sym_end,
      sym_NAME,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [599] = 1,
    ACTIONS(73), 4,
      ts_builtin_sym_end,
      sym__SINGLE_UNIT,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [606] = 1,
    ACTIONS(126), 4,
      ts_builtin_sym_end,
      sym__SINGLE_UNIT,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [613] = 3,
    ACTIONS(146), 1,
      anon_sym_COMMA,
    STATE(48), 1,
      aux_sym_args_repeat1,
    ACTIONS(144), 2,
      sym_NAME,
      anon_sym_RPAREN,
  [624] = 1,
    ACTIONS(149), 4,
      ts_builtin_sym_end,
      sym_NAME,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [631] = 3,
    ACTIONS(136), 1,
      anon_sym_COMMA,
    STATE(41), 1,
      aux_sym_args_repeat1,
    ACTIONS(151), 2,
      sym_NAME,
      anon_sym_RPAREN,
  [642] = 2,
    ACTIONS(79), 1,
      sym__SINGLE_UNIT,
    ACTIONS(73), 3,
      sym_NAME,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [651] = 1,
    ACTIONS(153), 4,
      ts_builtin_sym_end,
      sym__SINGLE_UNIT,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [658] = 2,
    ACTIONS(122), 1,
      sym__SINGLE_UNIT,
    ACTIONS(118), 3,
      sym_NAME,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [667] = 4,
    ACTIONS(155), 1,
      sym_NAME,
    ACTIONS(157), 1,
      anon_sym_RPAREN,
    STATE(59), 1,
      sym_kwarg,
    STATE(68), 1,
      sym_kwargs,
  [680] = 2,
    ACTIONS(159), 1,
      sym__SINGLE_UNIT,
    ACTIONS(153), 3,
      sym_NAME,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [689] = 1,
    ACTIONS(144), 3,
      sym_NAME,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [695] = 3,
    ACTIONS(161), 1,
      anon_sym_RPAREN,
    ACTIONS(163), 1,
      anon_sym_COMMA,
    STATE(57), 1,
      aux_sym_kwargs_repeat1,
  [705] = 3,
    ACTIONS(166), 1,
      anon_sym_RPAREN,
    ACTIONS(168), 1,
      anon_sym_COMMA,
    STATE(57), 1,
      aux_sym_kwargs_repeat1,
  [715] = 3,
    ACTIONS(168), 1,
      anon_sym_COMMA,
    ACTIONS(170), 1,
      anon_sym_RPAREN,
    STATE(58), 1,
      aux_sym_kwargs_repeat1,
  [725] = 3,
    ACTIONS(172), 1,
      sym__DIGITS,
    ACTIONS(174), 1,
      sym__SIGN,
    STATE(19), 1,
      sym_integer,
  [735] = 2,
    ACTIONS(83), 1,
      sym__SINGLE_UNIT,
    STATE(20), 1,
      sym_unit_term,
  [742] = 2,
    ACTIONS(155), 1,
      sym_NAME,
    STATE(64), 1,
      sym_kwarg,
  [749] = 2,
    ACTIONS(83), 1,
      sym__SINGLE_UNIT,
    STATE(32), 1,
      sym_unit_term,
  [756] = 1,
    ACTIONS(161), 2,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [761] = 2,
    ACTIONS(176), 1,
      anon_sym_DOT,
    ACTIONS(178), 1,
      sym__DIGITS,
  [768] = 2,
    ACTIONS(180), 1,
      anon_sym_DOT,
    ACTIONS(182), 1,
      sym__DIGITS,
  [775] = 1,
    ACTIONS(184), 2,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [780] = 1,
    ACTIONS(186), 1,
      anon_sym_RPAREN,
  [784] = 1,
    ACTIONS(188), 1,
      sym__DIGITS,
  [788] = 1,
    ACTIONS(190), 1,
      sym__DIGITS,
  [792] = 1,
    ACTIONS(192), 1,
      sym__DIGITS,
  [796] = 1,
    ACTIONS(194), 1,
      ts_builtin_sym_end,
  [800] = 1,
    ACTIONS(196), 1,
      anon_sym_RPAREN,
  [804] = 1,
    ACTIONS(198), 1,
      sym__DIGITS,
  [808] = 1,
    ACTIONS(60), 1,
      sym__DIGITS,
  [812] = 1,
    ACTIONS(41), 1,
      anon_sym_EQ,
  [816] = 1,
    ACTIONS(200), 1,
      sym__DIGITS,
  [820] = 1,
    ACTIONS(202), 1,
      sym__DIGITS,
  [824] = 1,
    ACTIONS(204), 1,
      sym__DIGITS,
  [828] = 1,
    ACTIONS(206), 1,
      sym_NAME,
  [832] = 1,
    ACTIONS(208), 1,
      sym__DIGITS,
  [836] = 1,
    ACTIONS(106), 1,
      sym__DIGITS,
  [840] = 1,
    ACTIONS(210), 1,
      sym__DIGITS,
  [844] = 1,
    ACTIONS(212), 1,
      sym__DIGITS,
  [848] = 1,
    ACTIONS(214), 1,
      sym__DIGITS,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 39,
  [SMALL_STATE(4)] = 66,
  [SMALL_STATE(5)] = 93,
  [SMALL_STATE(6)] = 112,
  [SMALL_STATE(7)] = 131,
  [SMALL_STATE(8)] = 146,
  [SMALL_STATE(9)] = 164,
  [SMALL_STATE(10)] = 180,
  [SMALL_STATE(11)] = 194,
  [SMALL_STATE(12)] = 209,
  [SMALL_STATE(13)] = 224,
  [SMALL_STATE(14)] = 239,
  [SMALL_STATE(15)] = 252,
  [SMALL_STATE(16)] = 267,
  [SMALL_STATE(17)] = 282,
  [SMALL_STATE(18)] = 295,
  [SMALL_STATE(19)] = 304,
  [SMALL_STATE(20)] = 313,
  [SMALL_STATE(21)] = 322,
  [SMALL_STATE(22)] = 335,
  [SMALL_STATE(23)] = 348,
  [SMALL_STATE(24)] = 357,
  [SMALL_STATE(25)] = 374,
  [SMALL_STATE(26)] = 389,
  [SMALL_STATE(27)] = 404,
  [SMALL_STATE(28)] = 421,
  [SMALL_STATE(29)] = 436,
  [SMALL_STATE(30)] = 449,
  [SMALL_STATE(31)] = 457,
  [SMALL_STATE(32)] = 469,
  [SMALL_STATE(33)] = 477,
  [SMALL_STATE(34)] = 489,
  [SMALL_STATE(35)] = 501,
  [SMALL_STATE(36)] = 513,
  [SMALL_STATE(37)] = 525,
  [SMALL_STATE(38)] = 537,
  [SMALL_STATE(39)] = 546,
  [SMALL_STATE(40)] = 553,
  [SMALL_STATE(41)] = 560,
  [SMALL_STATE(42)] = 571,
  [SMALL_STATE(43)] = 578,
  [SMALL_STATE(44)] = 585,
  [SMALL_STATE(45)] = 592,
  [SMALL_STATE(46)] = 599,
  [SMALL_STATE(47)] = 606,
  [SMALL_STATE(48)] = 613,
  [SMALL_STATE(49)] = 624,
  [SMALL_STATE(50)] = 631,
  [SMALL_STATE(51)] = 642,
  [SMALL_STATE(52)] = 651,
  [SMALL_STATE(53)] = 658,
  [SMALL_STATE(54)] = 667,
  [SMALL_STATE(55)] = 680,
  [SMALL_STATE(56)] = 689,
  [SMALL_STATE(57)] = 695,
  [SMALL_STATE(58)] = 705,
  [SMALL_STATE(59)] = 715,
  [SMALL_STATE(60)] = 725,
  [SMALL_STATE(61)] = 735,
  [SMALL_STATE(62)] = 742,
  [SMALL_STATE(63)] = 749,
  [SMALL_STATE(64)] = 756,
  [SMALL_STATE(65)] = 761,
  [SMALL_STATE(66)] = 768,
  [SMALL_STATE(67)] = 775,
  [SMALL_STATE(68)] = 780,
  [SMALL_STATE(69)] = 784,
  [SMALL_STATE(70)] = 788,
  [SMALL_STATE(71)] = 792,
  [SMALL_STATE(72)] = 796,
  [SMALL_STATE(73)] = 800,
  [SMALL_STATE(74)] = 804,
  [SMALL_STATE(75)] = 808,
  [SMALL_STATE(76)] = 812,
  [SMALL_STATE(77)] = 816,
  [SMALL_STATE(78)] = 820,
  [SMALL_STATE(79)] = 824,
  [SMALL_STATE(80)] = 828,
  [SMALL_STATE(81)] = 832,
  [SMALL_STATE(82)] = 836,
  [SMALL_STATE(83)] = 840,
  [SMALL_STATE(84)] = 844,
  [SMALL_STATE(85)] = 848,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT(78),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(79),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [21] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_unit, 2, 0, 4),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [27] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_unit, 1, 0, 1),
  [29] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_unit_term, 1, 0, 1),
  [31] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_unit_term, 1, 0, 1),
  [33] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [35] = {.entry = {.count = 1, .reusable = true}}, SHIFT(80),
  [37] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_variable, 1, 0, 0),
  [39] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [41] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [43] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_unit_repeat1, 2, 0, 0),
  [45] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_unit_repeat1, 2, 0, 0), SHIFT_REPEAT(61),
  [48] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_integer, 1, 0, 0),
  [50] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [52] = {.entry = {.count = 1, .reusable = false}}, SHIFT(69),
  [54] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_float, 1, 0, 0),
  [56] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_float, 2, 0, 0),
  [58] = {.entry = {.count = 1, .reusable = false}}, SHIFT(77),
  [60] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [62] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_float, 2, 0, 0),
  [64] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_integer, 2, 0, 0),
  [66] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [68] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_variable_repeat1, 2, 0, 0),
  [70] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_variable_repeat1, 2, 0, 0), SHIFT_REPEAT(80),
  [73] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_float, 3, 0, 0),
  [75] = {.entry = {.count = 1, .reusable = false}}, SHIFT(70),
  [77] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [79] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_float, 3, 0, 0),
  [81] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__number, 1, 0, 0),
  [83] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [85] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_unit, 2, 0, 5),
  [87] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_unit_term, 3, 0, 8),
  [89] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_unit, 3, 0, 9),
  [91] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_unit_repeat2, 2, 0, 0),
  [93] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_unit_repeat2, 2, 0, 0), SHIFT_REPEAT(63),
  [96] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [98] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_integer, 1, 0, 0),
  [100] = {.entry = {.count = 1, .reusable = false}}, SHIFT(81),
  [102] = {.entry = {.count = 1, .reusable = false}}, SHIFT(7),
  [104] = {.entry = {.count = 1, .reusable = false}}, SHIFT(83),
  [106] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [108] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [110] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_integer, 2, 0, 0),
  [112] = {.entry = {.count = 1, .reusable = false}}, SHIFT(84),
  [114] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [116] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_variable, 2, 0, 0),
  [118] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_float, 4, 0, 0),
  [120] = {.entry = {.count = 1, .reusable = false}}, SHIFT(71),
  [122] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_float, 4, 0, 0),
  [124] = {.entry = {.count = 1, .reusable = false}}, SHIFT(85),
  [126] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_float, 6, 0, 0),
  [128] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_float, 6, 0, 0),
  [130] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_call, 4, 0, 6),
  [132] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_quantity, 2, 0, 2),
  [134] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_args, 2, 0, 0),
  [136] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [138] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_call, 4, 0, 7),
  [140] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression, 1, 0, 0),
  [142] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_call, 3, 0, 3),
  [144] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_args_repeat1, 2, 0, 0),
  [146] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_args_repeat1, 2, 0, 0), SHIFT_REPEAT(4),
  [149] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_call, 5, 0, 10),
  [151] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_args, 1, 0, 0),
  [153] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_float, 5, 0, 0),
  [155] = {.entry = {.count = 1, .reusable = true}}, SHIFT(76),
  [157] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [159] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_float, 5, 0, 0),
  [161] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_kwargs_repeat1, 2, 0, 0),
  [163] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_kwargs_repeat1, 2, 0, 0), SHIFT_REPEAT(62),
  [166] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_kwargs, 2, 0, 0),
  [168] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [170] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_kwargs, 1, 0, 0),
  [172] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [174] = {.entry = {.count = 1, .reusable = true}}, SHIFT(74),
  [176] = {.entry = {.count = 1, .reusable = true}}, SHIFT(75),
  [178] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [180] = {.entry = {.count = 1, .reusable = true}}, SHIFT(82),
  [182] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [184] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_kwarg, 3, 0, 0),
  [186] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [188] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [190] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [192] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [194] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [196] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [198] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [200] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [202] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [204] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [206] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [208] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [210] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [212] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [214] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_caqtus(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
